// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pool/v0/network.proto

package ppool // import "github.com/n0stack/proto.go/pool/v0"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import v01 "github.com/n0stack/proto.go/resource/v0"
import v0 "github.com/n0stack/proto.go/v0"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NetworkStatus_NetworkState int32

const (
	// falied state because failed some process on API.
	NetworkStatus_FAILED NetworkStatus_NetworkState = 0
	// unknown state because failed to connect for scheduled node after RUNNING.
	NetworkStatus_UNKNOWN   NetworkStatus_NetworkState = 1
	NetworkStatus_AVAILABLE NetworkStatus_NetworkState = 2
)

var NetworkStatus_NetworkState_name = map[int32]string{
	0: "FAILED",
	1: "UNKNOWN",
	2: "AVAILABLE",
}
var NetworkStatus_NetworkState_value = map[string]int32{
	"FAILED":    0,
	"UNKNOWN":   1,
	"AVAILABLE": 2,
}

func (x NetworkStatus_NetworkState) String() string {
	return proto.EnumName(NetworkStatus_NetworkState_name, int32(x))
}
func (NetworkStatus_NetworkState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{2, 0}
}

type Network struct {
	Metadata             *v0.Metadata   `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Spec                 *NetworkSpec   `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status               *NetworkStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{0}
}
func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (dst *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(dst, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetMetadata() *v0.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Network) GetSpec() *NetworkSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Network) GetStatus() *NetworkStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type NetworkSpec struct {
	Ipv4Cidr             string   `protobuf:"bytes,1,opt,name=ipv4_cidr,json=ipv4Cidr" json:"ipv4_cidr,omitempty"`
	Ipv6Cidr             string   `protobuf:"bytes,2,opt,name=ipv6_cidr,json=ipv6Cidr" json:"ipv6_cidr,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkSpec) Reset()         { *m = NetworkSpec{} }
func (m *NetworkSpec) String() string { return proto.CompactTextString(m) }
func (*NetworkSpec) ProtoMessage()    {}
func (*NetworkSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{1}
}
func (m *NetworkSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkSpec.Unmarshal(m, b)
}
func (m *NetworkSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkSpec.Marshal(b, m, deterministic)
}
func (dst *NetworkSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkSpec.Merge(dst, src)
}
func (m *NetworkSpec) XXX_Size() int {
	return xxx_messageInfo_NetworkSpec.Size(m)
}
func (m *NetworkSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkSpec.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkSpec proto.InternalMessageInfo

func (m *NetworkSpec) GetIpv4Cidr() string {
	if m != nil {
		return m.Ipv4Cidr
	}
	return ""
}

func (m *NetworkSpec) GetIpv6Cidr() string {
	if m != nil {
		return m.Ipv6Cidr
	}
	return ""
}

func (m *NetworkSpec) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type NetworkStatus struct {
	State                     NetworkStatus_NetworkState       `protobuf:"varint,1,opt,name=state,enum=n0stack.pool.NetworkStatus_NetworkState" json:"state,omitempty"`
	ReservedNetworkInterfaces map[string]*v01.NetworkInterface `protobuf:"bytes,2,rep,name=reserved_network_interfaces,json=reservedNetworkInterfaces" json:"reserved_network_interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral      struct{}                         `json:"-"`
	XXX_unrecognized          []byte                           `json:"-"`
	XXX_sizecache             int32                            `json:"-"`
}

func (m *NetworkStatus) Reset()         { *m = NetworkStatus{} }
func (m *NetworkStatus) String() string { return proto.CompactTextString(m) }
func (*NetworkStatus) ProtoMessage()    {}
func (*NetworkStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{2}
}
func (m *NetworkStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkStatus.Unmarshal(m, b)
}
func (m *NetworkStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkStatus.Marshal(b, m, deterministic)
}
func (dst *NetworkStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkStatus.Merge(dst, src)
}
func (m *NetworkStatus) XXX_Size() int {
	return xxx_messageInfo_NetworkStatus.Size(m)
}
func (m *NetworkStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkStatus proto.InternalMessageInfo

func (m *NetworkStatus) GetState() NetworkStatus_NetworkState {
	if m != nil {
		return m.State
	}
	return NetworkStatus_FAILED
}

func (m *NetworkStatus) GetReservedNetworkInterfaces() map[string]*v01.NetworkInterface {
	if m != nil {
		return m.ReservedNetworkInterfaces
	}
	return nil
}

type ListNetworksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNetworksRequest) Reset()         { *m = ListNetworksRequest{} }
func (m *ListNetworksRequest) String() string { return proto.CompactTextString(m) }
func (*ListNetworksRequest) ProtoMessage()    {}
func (*ListNetworksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{3}
}
func (m *ListNetworksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNetworksRequest.Unmarshal(m, b)
}
func (m *ListNetworksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNetworksRequest.Marshal(b, m, deterministic)
}
func (dst *ListNetworksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNetworksRequest.Merge(dst, src)
}
func (m *ListNetworksRequest) XXX_Size() int {
	return xxx_messageInfo_ListNetworksRequest.Size(m)
}
func (m *ListNetworksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNetworksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNetworksRequest proto.InternalMessageInfo

type ListNetworksResponse struct {
	Networks             []*Network `protobuf:"bytes,1,rep,name=networks" json:"networks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListNetworksResponse) Reset()         { *m = ListNetworksResponse{} }
func (m *ListNetworksResponse) String() string { return proto.CompactTextString(m) }
func (*ListNetworksResponse) ProtoMessage()    {}
func (*ListNetworksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{4}
}
func (m *ListNetworksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNetworksResponse.Unmarshal(m, b)
}
func (m *ListNetworksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNetworksResponse.Marshal(b, m, deterministic)
}
func (dst *ListNetworksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNetworksResponse.Merge(dst, src)
}
func (m *ListNetworksResponse) XXX_Size() int {
	return xxx_messageInfo_ListNetworksResponse.Size(m)
}
func (m *ListNetworksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNetworksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNetworksResponse proto.InternalMessageInfo

func (m *ListNetworksResponse) GetNetworks() []*Network {
	if m != nil {
		return m.Networks
	}
	return nil
}

type GetNetworkRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNetworkRequest) Reset()         { *m = GetNetworkRequest{} }
func (m *GetNetworkRequest) String() string { return proto.CompactTextString(m) }
func (*GetNetworkRequest) ProtoMessage()    {}
func (*GetNetworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{5}
}
func (m *GetNetworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkRequest.Unmarshal(m, b)
}
func (m *GetNetworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkRequest.Marshal(b, m, deterministic)
}
func (dst *GetNetworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkRequest.Merge(dst, src)
}
func (m *GetNetworkRequest) XXX_Size() int {
	return xxx_messageInfo_GetNetworkRequest.Size(m)
}
func (m *GetNetworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkRequest proto.InternalMessageInfo

func (m *GetNetworkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ApplyNetworkRequest struct {
	Metadata             *v0.Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Spec                 *NetworkSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ApplyNetworkRequest) Reset()         { *m = ApplyNetworkRequest{} }
func (m *ApplyNetworkRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyNetworkRequest) ProtoMessage()    {}
func (*ApplyNetworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{6}
}
func (m *ApplyNetworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyNetworkRequest.Unmarshal(m, b)
}
func (m *ApplyNetworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyNetworkRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyNetworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyNetworkRequest.Merge(dst, src)
}
func (m *ApplyNetworkRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyNetworkRequest.Size(m)
}
func (m *ApplyNetworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyNetworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyNetworkRequest proto.InternalMessageInfo

func (m *ApplyNetworkRequest) GetMetadata() *v0.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ApplyNetworkRequest) GetSpec() *NetworkSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type DeleteNetworkRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNetworkRequest) Reset()         { *m = DeleteNetworkRequest{} }
func (m *DeleteNetworkRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNetworkRequest) ProtoMessage()    {}
func (*DeleteNetworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{7}
}
func (m *DeleteNetworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNetworkRequest.Unmarshal(m, b)
}
func (m *DeleteNetworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNetworkRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteNetworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNetworkRequest.Merge(dst, src)
}
func (m *DeleteNetworkRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNetworkRequest.Size(m)
}
func (m *DeleteNetworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNetworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNetworkRequest proto.InternalMessageInfo

func (m *DeleteNetworkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReserveNetworkInterfaceRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	NetworkInterfaceName string            `protobuf:"bytes,2,opt,name=network_interface_name,json=networkInterfaceName" json:"network_interface_name,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 以下 optional
	HardwareAddress      string   `protobuf:"bytes,4,opt,name=hardware_address,json=hardwareAddress" json:"hardware_address,omitempty"`
	Ipv4Address          string   `protobuf:"bytes,5,opt,name=ipv4_address,json=ipv4Address" json:"ipv4_address,omitempty"`
	Ipv6Address          string   `protobuf:"bytes,6,opt,name=ipv6_address,json=ipv6Address" json:"ipv6_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveNetworkInterfaceRequest) Reset()         { *m = ReserveNetworkInterfaceRequest{} }
func (m *ReserveNetworkInterfaceRequest) String() string { return proto.CompactTextString(m) }
func (*ReserveNetworkInterfaceRequest) ProtoMessage()    {}
func (*ReserveNetworkInterfaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{8}
}
func (m *ReserveNetworkInterfaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveNetworkInterfaceRequest.Unmarshal(m, b)
}
func (m *ReserveNetworkInterfaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveNetworkInterfaceRequest.Marshal(b, m, deterministic)
}
func (dst *ReserveNetworkInterfaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveNetworkInterfaceRequest.Merge(dst, src)
}
func (m *ReserveNetworkInterfaceRequest) XXX_Size() int {
	return xxx_messageInfo_ReserveNetworkInterfaceRequest.Size(m)
}
func (m *ReserveNetworkInterfaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveNetworkInterfaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveNetworkInterfaceRequest proto.InternalMessageInfo

func (m *ReserveNetworkInterfaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReserveNetworkInterfaceRequest) GetNetworkInterfaceName() string {
	if m != nil {
		return m.NetworkInterfaceName
	}
	return ""
}

func (m *ReserveNetworkInterfaceRequest) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *ReserveNetworkInterfaceRequest) GetHardwareAddress() string {
	if m != nil {
		return m.HardwareAddress
	}
	return ""
}

func (m *ReserveNetworkInterfaceRequest) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *ReserveNetworkInterfaceRequest) GetIpv6Address() string {
	if m != nil {
		return m.Ipv6Address
	}
	return ""
}

type ReleaseNetworkInterfaceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	NetworkInterfaceName string   `protobuf:"bytes,2,opt,name=network_interface_name,json=networkInterfaceName" json:"network_interface_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseNetworkInterfaceRequest) Reset()         { *m = ReleaseNetworkInterfaceRequest{} }
func (m *ReleaseNetworkInterfaceRequest) String() string { return proto.CompactTextString(m) }
func (*ReleaseNetworkInterfaceRequest) ProtoMessage()    {}
func (*ReleaseNetworkInterfaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_8dc2a267a17236d7, []int{9}
}
func (m *ReleaseNetworkInterfaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseNetworkInterfaceRequest.Unmarshal(m, b)
}
func (m *ReleaseNetworkInterfaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseNetworkInterfaceRequest.Marshal(b, m, deterministic)
}
func (dst *ReleaseNetworkInterfaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseNetworkInterfaceRequest.Merge(dst, src)
}
func (m *ReleaseNetworkInterfaceRequest) XXX_Size() int {
	return xxx_messageInfo_ReleaseNetworkInterfaceRequest.Size(m)
}
func (m *ReleaseNetworkInterfaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseNetworkInterfaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseNetworkInterfaceRequest proto.InternalMessageInfo

func (m *ReleaseNetworkInterfaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReleaseNetworkInterfaceRequest) GetNetworkInterfaceName() string {
	if m != nil {
		return m.NetworkInterfaceName
	}
	return ""
}

func init() {
	proto.RegisterType((*Network)(nil), "n0stack.pool.Network")
	proto.RegisterType((*NetworkSpec)(nil), "n0stack.pool.NetworkSpec")
	proto.RegisterType((*NetworkStatus)(nil), "n0stack.pool.NetworkStatus")
	proto.RegisterMapType((map[string]*v01.NetworkInterface)(nil), "n0stack.pool.NetworkStatus.ReservedNetworkInterfacesEntry")
	proto.RegisterType((*ListNetworksRequest)(nil), "n0stack.pool.ListNetworksRequest")
	proto.RegisterType((*ListNetworksResponse)(nil), "n0stack.pool.ListNetworksResponse")
	proto.RegisterType((*GetNetworkRequest)(nil), "n0stack.pool.GetNetworkRequest")
	proto.RegisterType((*ApplyNetworkRequest)(nil), "n0stack.pool.ApplyNetworkRequest")
	proto.RegisterType((*DeleteNetworkRequest)(nil), "n0stack.pool.DeleteNetworkRequest")
	proto.RegisterType((*ReserveNetworkInterfaceRequest)(nil), "n0stack.pool.ReserveNetworkInterfaceRequest")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.pool.ReserveNetworkInterfaceRequest.AnnotationsEntry")
	proto.RegisterType((*ReleaseNetworkInterfaceRequest)(nil), "n0stack.pool.ReleaseNetworkInterfaceRequest")
	proto.RegisterEnum("n0stack.pool.NetworkStatus_NetworkState", NetworkStatus_NetworkState_name, NetworkStatus_NetworkState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NetworkService service

type NetworkServiceClient interface {
	ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
	GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*Network, error)
	ApplyNetwork(ctx context.Context, in *ApplyNetworkRequest, opts ...grpc.CallOption) (*Network, error)
	DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ReserveNetworkInterface(ctx context.Context, in *ReserveNetworkInterfaceRequest, opts ...grpc.CallOption) (*v01.NetworkInterface, error)
	ReleaseNetworkInterface(ctx context.Context, in *ReleaseNetworkInterfaceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type networkServiceClient struct {
	cc *grpc.ClientConn
}

func NewNetworkServiceClient(cc *grpc.ClientConn) NetworkServiceClient {
	return &networkServiceClient{cc}
}

func (c *networkServiceClient) ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	out := new(ListNetworksResponse)
	err := grpc.Invoke(ctx, "/n0stack.pool.NetworkService/ListNetworks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*Network, error) {
	out := new(Network)
	err := grpc.Invoke(ctx, "/n0stack.pool.NetworkService/GetNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) ApplyNetwork(ctx context.Context, in *ApplyNetworkRequest, opts ...grpc.CallOption) (*Network, error) {
	out := new(Network)
	err := grpc.Invoke(ctx, "/n0stack.pool.NetworkService/ApplyNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/n0stack.pool.NetworkService/DeleteNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) ReserveNetworkInterface(ctx context.Context, in *ReserveNetworkInterfaceRequest, opts ...grpc.CallOption) (*v01.NetworkInterface, error) {
	out := new(v01.NetworkInterface)
	err := grpc.Invoke(ctx, "/n0stack.pool.NetworkService/ReserveNetworkInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) ReleaseNetworkInterface(ctx context.Context, in *ReleaseNetworkInterfaceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/n0stack.pool.NetworkService/ReleaseNetworkInterface", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NetworkService service

type NetworkServiceServer interface {
	ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	GetNetwork(context.Context, *GetNetworkRequest) (*Network, error)
	ApplyNetwork(context.Context, *ApplyNetworkRequest) (*Network, error)
	DeleteNetwork(context.Context, *DeleteNetworkRequest) (*empty.Empty, error)
	ReserveNetworkInterface(context.Context, *ReserveNetworkInterfaceRequest) (*v01.NetworkInterface, error)
	ReleaseNetworkInterface(context.Context, *ReleaseNetworkInterfaceRequest) (*empty.Empty, error)
}

func RegisterNetworkServiceServer(s *grpc.Server, srv NetworkServiceServer) {
	s.RegisterService(&_NetworkService_serviceDesc, srv)
}

func _NetworkService_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.pool.NetworkService/ListNetworks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).ListNetworks(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.pool.NetworkService/GetNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).GetNetwork(ctx, req.(*GetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_ApplyNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).ApplyNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.pool.NetworkService/ApplyNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).ApplyNetwork(ctx, req.(*ApplyNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_DeleteNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).DeleteNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.pool.NetworkService/DeleteNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).DeleteNetwork(ctx, req.(*DeleteNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_ReserveNetworkInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveNetworkInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).ReserveNetworkInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.pool.NetworkService/ReserveNetworkInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).ReserveNetworkInterface(ctx, req.(*ReserveNetworkInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_ReleaseNetworkInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseNetworkInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).ReleaseNetworkInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.pool.NetworkService/ReleaseNetworkInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).ReleaseNetworkInterface(ctx, req.(*ReleaseNetworkInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "n0stack.pool.NetworkService",
	HandlerType: (*NetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNetworks",
			Handler:    _NetworkService_ListNetworks_Handler,
		},
		{
			MethodName: "GetNetwork",
			Handler:    _NetworkService_GetNetwork_Handler,
		},
		{
			MethodName: "ApplyNetwork",
			Handler:    _NetworkService_ApplyNetwork_Handler,
		},
		{
			MethodName: "DeleteNetwork",
			Handler:    _NetworkService_DeleteNetwork_Handler,
		},
		{
			MethodName: "ReserveNetworkInterface",
			Handler:    _NetworkService_ReserveNetworkInterface_Handler,
		},
		{
			MethodName: "ReleaseNetworkInterface",
			Handler:    _NetworkService_ReleaseNetworkInterface_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pool/v0/network.proto",
}

func init() { proto.RegisterFile("pool/v0/network.proto", fileDescriptor_network_8dc2a267a17236d7) }

var fileDescriptor_network_8dc2a267a17236d7 = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x51, 0x4f, 0x1a, 0x4b,
	0x14, 0x06, 0x44, 0x94, 0x03, 0x7a, 0x71, 0x44, 0x2f, 0x2e, 0xc9, 0xbd, 0xba, 0xf7, 0xe1, 0xea,
	0xbd, 0x75, 0xb1, 0x68, 0x88, 0xb1, 0xa9, 0x09, 0x56, 0x6c, 0x68, 0x91, 0x26, 0xdb, 0xb4, 0x26,
	0x7d, 0x21, 0xe3, 0xee, 0x88, 0x5b, 0x61, 0x77, 0x3b, 0x33, 0x60, 0xe8, 0x6f, 0x69, 0xfa, 0x2f,
	0xfb, 0xd6, 0x87, 0x66, 0x67, 0x67, 0xd7, 0x05, 0x16, 0x62, 0x1f, 0x7c, 0x1b, 0xce, 0xf9, 0xbe,
	0x6f, 0xce, 0x9c, 0x39, 0x1f, 0xb3, 0xb0, 0xe1, 0x3a, 0x4e, 0xaf, 0x32, 0x3c, 0xa8, 0xd8, 0x84,
	0xdf, 0x3b, 0xf4, 0x4e, 0x73, 0xa9, 0xc3, 0x1d, 0x94, 0xb7, 0x0f, 0x18, 0xc7, 0xc6, 0x9d, 0xe6,
	0xa5, 0x95, 0x72, 0xd7, 0x71, 0xba, 0x3d, 0x52, 0x11, 0xb9, 0xeb, 0xc1, 0x4d, 0x85, 0xf4, 0x5d,
	0x3e, 0xf2, 0xa1, 0xca, 0xda, 0xf0, 0xa0, 0xd2, 0x27, 0x1c, 0x9b, 0x98, 0x63, 0x19, 0xfa, 0x87,
	0x12, 0xe6, 0x0c, 0xa8, 0x41, 0x22, 0xc2, 0x1d, 0xcb, 0xe6, 0x84, 0xde, 0x60, 0x83, 0xf8, 0x20,
	0xf5, 0x5b, 0x12, 0x96, 0xda, 0x7e, 0x0e, 0xed, 0xc3, 0x72, 0x20, 0x51, 0x4a, 0x6e, 0x27, 0x77,
	0x73, 0xd5, 0x35, 0x2d, 0xa8, 0xe0, 0x52, 0x26, 0xf4, 0x10, 0x82, 0xf6, 0x21, 0xcd, 0x5c, 0x62,
	0x94, 0x52, 0x02, 0xba, 0xa5, 0x45, 0x8b, 0xd5, 0xa4, 0xe6, 0x7b, 0x97, 0x18, 0xba, 0x80, 0xa1,
	0x43, 0xc8, 0x30, 0x8e, 0xf9, 0x80, 0x95, 0x16, 0x04, 0xa1, 0x1c, 0x4f, 0x10, 0x10, 0x5d, 0x42,
	0xd5, 0x0e, 0xe4, 0x22, 0x4a, 0xa8, 0x0c, 0x59, 0xcb, 0x1d, 0x1e, 0x75, 0x0c, 0xcb, 0xa4, 0xa2,
	0xc4, 0xac, 0xbe, 0xec, 0x05, 0x5e, 0x59, 0x26, 0x95, 0xc9, 0x9a, 0x9f, 0x4c, 0x85, 0xc9, 0x9a,
	0x48, 0x6e, 0x42, 0xc6, 0x74, 0xfa, 0xd8, 0xb2, 0xc5, 0xee, 0x59, 0x5d, 0xfe, 0x52, 0x7f, 0xa4,
	0x60, 0x65, 0x6c, 0x6b, 0x74, 0x0a, 0x8b, 0xde, 0xe6, 0x44, 0xe8, 0xaf, 0x56, 0x77, 0xe7, 0x94,
	0x19, 0xfd, 0x45, 0x74, 0x9f, 0x86, 0xbe, 0x42, 0x99, 0x12, 0x46, 0xe8, 0x90, 0x98, 0x9d, 0xa9,
	0xae, 0xb3, 0x52, 0x6a, 0x7b, 0x61, 0x37, 0x57, 0x3d, 0x99, 0xa7, 0xaa, 0x4b, 0xba, 0x8c, 0x36,
	0x43, 0x72, 0xc3, 0xe6, 0x74, 0xa4, 0x6f, 0xd1, 0x59, 0x79, 0xc5, 0x85, 0xbf, 0xe6, 0x93, 0x51,
	0x01, 0x16, 0xee, 0xc8, 0x48, 0xf6, 0xce, 0x5b, 0xa2, 0x63, 0x58, 0x1c, 0xe2, 0xde, 0x80, 0xc8,
	0x7b, 0x54, 0xc3, 0xca, 0x82, 0xf1, 0xd1, 0x26, 0xa5, 0x74, 0x9f, 0x70, 0x92, 0x3a, 0x4e, 0xaa,
	0x35, 0xc8, 0x47, 0x9b, 0x80, 0x00, 0x32, 0x17, 0xf5, 0x66, 0xab, 0x71, 0x5e, 0x48, 0xa0, 0x1c,
	0x2c, 0x7d, 0x68, 0xbf, 0x6d, 0xbf, 0xbb, 0x6a, 0x17, 0x92, 0x68, 0x05, 0xb2, 0xf5, 0x8f, 0xf5,
	0x66, 0xab, 0x7e, 0xd6, 0x6a, 0x14, 0x52, 0xea, 0x06, 0xac, 0xb7, 0x2c, 0xc6, 0x25, 0x97, 0xe9,
	0xe4, 0xcb, 0x80, 0x30, 0xae, 0x36, 0xa1, 0x38, 0x1e, 0x66, 0xae, 0x63, 0x33, 0x82, 0x9e, 0xc3,
	0xb2, 0xec, 0x25, 0x2b, 0x25, 0x45, 0x07, 0x37, 0x62, 0x3b, 0xa8, 0x87, 0x30, 0xf5, 0x5f, 0x58,
	0x7b, 0x4d, 0x02, 0x25, 0xa9, 0x8f, 0x10, 0xa4, 0x6d, 0xdc, 0x27, 0xf2, 0xfc, 0x62, 0xad, 0x32,
	0x58, 0xaf, 0xbb, 0x6e, 0x6f, 0x34, 0x01, 0x7d, 0x52, 0x37, 0xa8, 0xff, 0x41, 0xf1, 0x9c, 0xf4,
	0x08, 0x27, 0x8f, 0x28, 0xf0, 0x67, 0x2a, 0xbc, 0xd6, 0xa9, 0xab, 0x98, 0x4d, 0x43, 0x47, 0xb0,
	0x39, 0x35, 0x7f, 0x1d, 0x81, 0xf2, 0xcd, 0x51, 0xb4, 0x27, 0xc4, 0xda, 0x1e, 0xab, 0x03, 0x39,
	0x6c, 0xdb, 0x0e, 0xc7, 0xdc, 0x72, 0x6c, 0xcf, 0xab, 0x5e, 0xb3, 0x5f, 0x8e, 0x1f, 0x67, 0x7e,
	0x31, 0x5a, 0xfd, 0x81, 0xef, 0x4f, 0x6c, 0x54, 0x11, 0xed, 0x41, 0xe1, 0x16, 0x53, 0xf3, 0x1e,
	0x53, 0xd2, 0xc1, 0xa6, 0x49, 0x09, 0x63, 0xa5, 0xb4, 0x28, 0xe8, 0x8f, 0x20, 0x5e, 0xf7, 0xc3,
	0x68, 0x07, 0xf2, 0xc2, 0xee, 0x01, 0x6c, 0x51, 0xc0, 0x72, 0x5e, 0x6c, 0x1c, 0x52, 0x0b, 0x21,
	0x99, 0x10, 0x52, 0x93, 0x10, 0xe5, 0x14, 0x0a, 0x93, 0x15, 0xc5, 0xd8, 0xa0, 0x18, 0xb5, 0x41,
	0x36, 0x3a, 0xe2, 0x9f, 0xbd, 0xee, 0xf7, 0x08, 0x66, 0x4f, 0xdf, 0xfd, 0xea, 0xf7, 0x34, 0xac,
	0x06, 0xc3, 0x42, 0xe8, 0xd0, 0x32, 0x08, 0xba, 0x82, 0x7c, 0xd4, 0x12, 0x68, 0x67, 0xfc, 0x2e,
	0x62, 0x5c, 0xa4, 0xa8, 0xf3, 0x20, 0xbe, 0xa3, 0xd4, 0x04, 0xba, 0x00, 0x78, 0x30, 0x08, 0xfa,
	0x7b, 0x9c, 0x33, 0x65, 0x1d, 0x25, 0xde, 0x70, 0x6a, 0x02, 0xbd, 0x81, 0x7c, 0xd4, 0x3f, 0x93,
	0x05, 0xc6, 0x78, 0x6b, 0xb6, 0xd6, 0x25, 0xac, 0x8c, 0xd9, 0x02, 0x4d, 0x1c, 0x25, 0xce, 0x33,
	0xca, 0xa6, 0xe6, 0xbf, 0x8c, 0x5a, 0xf0, 0x32, 0x6a, 0x0d, 0xef, 0x65, 0x54, 0x13, 0xa8, 0x0f,
	0x7f, 0xce, 0x98, 0x55, 0xf4, 0xec, 0x77, 0x46, 0x5a, 0x79, 0xc4, 0xbf, 0xa2, 0x9a, 0x40, 0xd8,
	0xdb, 0x2e, 0x76, 0x52, 0xa6, 0xb7, 0x9b, 0x37, 0x50, 0xb3, 0x4f, 0x74, 0xf6, 0xff, 0xa7, 0xbd,
	0xae, 0xc5, 0x6f, 0x07, 0xd7, 0x9a, 0xe1, 0xf4, 0x2b, 0x52, 0xd3, 0xff, 0x24, 0xd0, 0xba, 0x4e,
	0x45, 0x7e, 0x47, 0xbc, 0x70, 0xbd, 0xc5, 0x75, 0x46, 0xc4, 0x0f, 0x7f, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xb7, 0x72, 0x1b, 0x36, 0x5f, 0x08, 0x00, 0x00,
}
