// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tap/v0/model.proto

/*
Package ptap is a generated protocol buffer package.

It is generated from these files:
	tap/v0/model.proto

It has these top-level messages:
	Tap
	Spec
	Status
	GetRequest
	ApplyRequest
	DeleteRequest
*/
package ptap

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Spec_NetworkType int32

const (
	Spec_FLAT Spec_NetworkType = 0
	Spec_VLAN Spec_NetworkType = 1
)

var Spec_NetworkType_name = map[int32]string{
	0: "FLAT",
	1: "VLAN",
}
var Spec_NetworkType_value = map[string]int32{
	"FLAT": 0,
	"VLAN": 1,
}

func (x Spec_NetworkType) String() string {
	return proto.EnumName(Spec_NetworkType_name, int32(x))
}
func (Spec_NetworkType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Tap struct {
	Id     string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Spec   *Spec   `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
	Status *Status `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
}

func (m *Tap) Reset()                    { *m = Tap{} }
func (m *Tap) String() string            { return proto.CompactTextString(m) }
func (*Tap) ProtoMessage()               {}
func (*Tap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Tap) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tap) GetSpec() *Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Tap) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type Spec struct {
	Type      Spec_NetworkType `protobuf:"varint,1,opt,name=type,enum=n0stack.tap.Spec_NetworkType" json:"type,omitempty"`
	NetworkId uint64           `protobuf:"varint,2,opt,name=network_id,json=networkId" json:"network_id,omitempty"`
}

func (m *Spec) Reset()                    { *m = Spec{} }
func (m *Spec) String() string            { return proto.CompactTextString(m) }
func (*Spec) ProtoMessage()               {}
func (*Spec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Spec) GetType() Spec_NetworkType {
	if m != nil {
		return m.Type
	}
	return Spec_FLAT
}

func (m *Spec) GetNetworkId() uint64 {
	if m != nil {
		return m.NetworkId
	}
	return 0
}

type Status struct {
	Tap    string `protobuf:"bytes,1,opt,name=tap" json:"tap,omitempty"`
	Bridge string `protobuf:"bytes,2,opt,name=bridge" json:"bridge,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Status) GetTap() string {
	if m != nil {
		return m.Tap
	}
	return ""
}

func (m *Status) GetBridge() string {
	if m != nil {
		return m.Bridge
	}
	return ""
}

type GetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ApplyRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Spec *Spec  `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
}

func (m *ApplyRequest) Reset()                    { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string            { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()               {}
func (*ApplyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApplyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplyRequest) GetSpec() *Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Tap)(nil), "n0stack.tap.Tap")
	proto.RegisterType((*Spec)(nil), "n0stack.tap.Spec")
	proto.RegisterType((*Status)(nil), "n0stack.tap.Status")
	proto.RegisterType((*GetRequest)(nil), "n0stack.tap.GetRequest")
	proto.RegisterType((*ApplyRequest)(nil), "n0stack.tap.ApplyRequest")
	proto.RegisterType((*DeleteRequest)(nil), "n0stack.tap.DeleteRequest")
	proto.RegisterEnum("n0stack.tap.Spec_NetworkType", Spec_NetworkType_name, Spec_NetworkType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TapService service

type TapServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Tap, error)
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*Tap, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type tapServiceClient struct {
	cc *grpc.ClientConn
}

func NewTapServiceClient(cc *grpc.ClientConn) TapServiceClient {
	return &tapServiceClient{cc}
}

func (c *tapServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Tap, error) {
	out := new(Tap)
	err := grpc.Invoke(ctx, "/n0stack.tap.TapService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapServiceClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*Tap, error) {
	out := new(Tap)
	err := grpc.Invoke(ctx, "/n0stack.tap.TapService/Apply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/n0stack.tap.TapService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TapService service

type TapServiceServer interface {
	Get(context.Context, *GetRequest) (*Tap, error)
	Apply(context.Context, *ApplyRequest) (*Tap, error)
	Delete(context.Context, *DeleteRequest) (*google_protobuf.Empty, error)
}

func RegisterTapServiceServer(s *grpc.Server, srv TapServiceServer) {
	s.RegisterService(&_TapService_serviceDesc, srv)
}

func _TapService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.tap.TapService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.tap.TapService/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapServiceServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.tap.TapService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TapService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "n0stack.tap.TapService",
	HandlerType: (*TapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _TapService_Get_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _TapService_Apply_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TapService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tap/v0/model.proto",
}

func init() { proto.RegisterFile("tap/v0/model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x52, 0x61, 0x6b, 0xd4, 0x40,
	0x10, 0xbd, 0xdc, 0xc5, 0xe0, 0xcd, 0x69, 0x39, 0x57, 0xa8, 0xe7, 0x69, 0xf1, 0x5c, 0x10, 0x4f,
	0x84, 0x4d, 0x8d, 0xe0, 0x17, 0x41, 0x38, 0xb1, 0x16, 0xa1, 0xf4, 0x43, 0x1a, 0xfc, 0xe0, 0x17,
	0xd9, 0x24, 0x63, 0x0c, 0xcd, 0x75, 0xc7, 0x64, 0x52, 0x09, 0xfe, 0x31, 0x7f, 0x9e, 0x64, 0x13,
	0xf5, 0xa2, 0xd6, 0x6f, 0x93, 0x79, 0x6f, 0x5e, 0xde, 0x3e, 0x1e, 0x08, 0xd6, 0xe4, 0x5f, 0x1e,
	0xfa, 0x5b, 0x93, 0x62, 0xa1, 0xa8, 0x34, 0x6c, 0xc4, 0xec, 0xe2, 0xb0, 0x62, 0x9d, 0x9c, 0x2b,
	0xd6, 0xb4, 0xbc, 0x97, 0x19, 0x93, 0x15, 0xe8, 0x5b, 0x28, 0xae, 0x3f, 0xf9, 0xb8, 0x25, 0x6e,
	0x3a, 0xa6, 0xcc, 0x61, 0x12, 0x69, 0x12, 0x7b, 0x30, 0xce, 0xd3, 0x85, 0xb3, 0x72, 0xd6, 0xd3,
	0x70, 0x9c, 0xa7, 0xe2, 0x11, 0xb8, 0x15, 0x61, 0xb2, 0x98, 0xac, 0x9c, 0xf5, 0x2c, 0xb8, 0xa5,
	0x76, 0xf4, 0xd4, 0x19, 0x61, 0x12, 0x5a, 0x58, 0x3c, 0x05, 0xaf, 0x62, 0xcd, 0x75, 0xb5, 0x70,
	0x2d, 0xf1, 0xf6, 0x90, 0x68, 0xa1, 0xb0, 0xa7, 0xc8, 0x6f, 0xe0, 0xb6, 0xa7, 0xe2, 0x19, 0xb8,
	0xdc, 0x10, 0xda, 0xbf, 0xed, 0x05, 0x07, 0x7f, 0x69, 0xab, 0x53, 0xe4, 0xaf, 0xa6, 0x3c, 0x8f,
	0x1a, 0xc2, 0xd0, 0x52, 0xc5, 0x01, 0xc0, 0x45, 0xb7, 0xfc, 0x98, 0xa7, 0x8b, 0xf1, 0xca, 0x59,
	0xbb, 0xe1, 0xb4, 0xdf, 0xbc, 0x4b, 0xe5, 0x43, 0x98, 0xed, 0xdc, 0x88, 0xeb, 0xe0, 0xbe, 0x3d,
	0xd9, 0x44, 0xf3, 0x51, 0x3b, 0xbd, 0x3f, 0xd9, 0x9c, 0xce, 0x1d, 0x19, 0x80, 0xd7, 0xd9, 0x11,
	0x73, 0x98, 0xb0, 0xa6, 0xfe, 0xad, 0xed, 0x28, 0xf6, 0xc1, 0x8b, 0xcb, 0x3c, 0xcd, 0xd0, 0x2a,
	0x4f, 0xc3, 0xfe, 0x4b, 0xde, 0x07, 0x38, 0x46, 0x0e, 0xf1, 0x4b, 0x8d, 0x15, 0xff, 0x19, 0x91,
	0x3c, 0x82, 0x1b, 0x1b, 0xa2, 0xa2, 0xb9, 0x02, 0xff, 0x15, 0xe1, 0xf8, 0xbf, 0x11, 0xca, 0x07,
	0x70, 0xf3, 0x0d, 0x16, 0xc8, 0x78, 0x85, 0x4e, 0xf0, 0xdd, 0x01, 0x88, 0x34, 0x9d, 0x61, 0x79,
	0x99, 0x27, 0x28, 0x02, 0x98, 0x1c, 0x23, 0x8b, 0x3b, 0x03, 0xbd, 0xdf, 0x36, 0x97, 0xf3, 0x01,
	0x10, 0x69, 0x92, 0x23, 0xf1, 0x02, 0xae, 0x59, 0xab, 0xe2, 0xee, 0x00, 0xdc, 0xb5, 0xff, 0xcf,
	0xbb, 0x57, 0xe0, 0x75, 0xde, 0xc4, 0x72, 0x80, 0x0e, 0x0c, 0x2f, 0xf7, 0x55, 0x57, 0x30, 0xf5,
	0xb3, 0x60, 0xea, 0xa8, 0x2d, 0x98, 0x1c, 0xbd, 0x7e, 0xf2, 0xe1, 0x71, 0x96, 0xf3, 0xe7, 0x3a,
	0x56, 0x89, 0xd9, 0xfa, 0xbd, 0x42, 0xd7, 0x43, 0x95, 0x19, 0xbf, 0x2b, 0xee, 0x4b, 0x62, 0x4d,
	0xb1, 0x67, 0xb7, 0xcf, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x53, 0x04, 0x6d, 0xd4, 0xce, 0x02,
	0x00, 0x00,
}
