// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node/v0/model.proto

/*
Package pnode is a generated protocol buffer package.

It is generated from these files:
	node/v0/model.proto

It has these top-level messages:
	Node
	Spec
	Status
	ListRequest
	ListResponse
	GetRequest
*/
package pnode

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import n0stack_metadata "github.com/n0stack/proto.go/metadata/v0"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Node struct {
	// MotherBoardのUUIDを用いる
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// n0core起動時のコマンドライン引数から取る
	Metadata *n0stack_metadata.Metadata `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	Spec     *Spec                      `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
	Status   *Status                    `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetMetadata() *n0stack_metadata.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Node) GetSpec() *Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Node) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type Spec struct {
}

func (m *Spec) Reset()                    { *m = Spec{} }
func (m *Spec) String() string            { return proto.CompactTextString(m) }
func (*Spec) ProtoMessage()               {}
func (*Spec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Status struct {
	Connection string `protobuf:"bytes,1,opt,name=connection" json:"connection,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Status) GetConnection() string {
	if m != nil {
		return m.Connection
	}
	return ""
}

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ListResponse struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type GetRequest struct {
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Node)(nil), "n0stack.node.Node")
	proto.RegisterType((*Spec)(nil), "n0stack.node.Spec")
	proto.RegisterType((*Status)(nil), "n0stack.node.Status")
	proto.RegisterType((*ListRequest)(nil), "n0stack.node.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "n0stack.node.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "n0stack.node.GetRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeService service

type NodeServiceClient interface {
	// clusterレベルのList
	// すべてのノードから同じ結果が帰ってくる必要がある
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// 自分のNodeオブジェクトを返す
	// IDを指定できるようにしたほうが統一感があるかもしれない
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Node, error)
}

type nodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewNodeServiceClient(cc *grpc.ClientConn) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/n0stack.node.NodeService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := grpc.Invoke(ctx, "/n0stack.node.NodeService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeService service

type NodeServiceServer interface {
	// clusterレベルのList
	// すべてのノードから同じ結果が帰ってくる必要がある
	List(context.Context, *ListRequest) (*ListResponse, error)
	// 自分のNodeオブジェクトを返す
	// IDを指定できるようにしたほうが統一感があるかもしれない
	Get(context.Context, *GetRequest) (*Node, error)
}

func RegisterNodeServiceServer(s *grpc.Server, srv NodeServiceServer) {
	s.RegisterService(&_NodeService_serviceDesc, srv)
}

func _NodeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.node.NodeService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.node.NodeService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "n0stack.node.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _NodeService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _NodeService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/v0/model.proto",
}

func init() { proto.RegisterFile("node/v0/model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xb1, 0x4e, 0xfb, 0x30,
	0x10, 0xc6, 0x9b, 0x36, 0xff, 0xe8, 0xcf, 0xb5, 0x30, 0x1c, 0x48, 0x84, 0x0c, 0xa8, 0xf2, 0x80,
	0x82, 0x40, 0x4e, 0x55, 0x04, 0x42, 0x62, 0x40, 0x62, 0xe9, 0x02, 0x0c, 0xe9, 0xc6, 0x96, 0x3a,
	0xa7, 0x12, 0x41, 0xed, 0x50, 0xbb, 0x7d, 0x03, 0xde, 0x84, 0x07, 0x45, 0x76, 0x12, 0x48, 0x4b,
	0xb7, 0xf3, 0x7d, 0xbf, 0xfb, 0xee, 0x93, 0x6d, 0x38, 0x94, 0x2a, 0xa7, 0x64, 0x3d, 0x4a, 0x16,
	0x2a, 0xa7, 0x77, 0x5e, 0x2e, 0x95, 0x51, 0x38, 0x90, 0x23, 0x6d, 0x32, 0xf1, 0xc6, 0xad, 0x18,
	0x1d, 0x2f, 0xc8, 0x64, 0x79, 0x66, 0xb2, 0x2d, 0x8c, 0x7d, 0x79, 0xe0, 0x3f, 0xab, 0x9c, 0xf0,
	0x00, 0xba, 0x45, 0x1e, 0x7a, 0x43, 0x2f, 0xde, 0x4b, 0xbb, 0x45, 0x8e, 0x37, 0xf0, 0xbf, 0x99,
	0x09, 0xbb, 0x43, 0x2f, 0xee, 0x8f, 0x23, 0xde, 0x58, 0x36, 0x02, 0x7f, 0xaa, 0x8b, 0xf4, 0x87,
	0xc5, 0x33, 0xf0, 0x75, 0x49, 0x22, 0xec, 0xb9, 0x19, 0xe4, 0xed, 0x18, 0x7c, 0x5a, 0x92, 0x48,
	0x9d, 0x8e, 0x97, 0x10, 0x68, 0x93, 0x99, 0x95, 0x0e, 0x7d, 0x47, 0x1e, 0x6d, 0x91, 0x4e, 0x4b,
	0x6b, 0x86, 0x05, 0xe0, 0xdb, 0x59, 0x16, 0x43, 0x50, 0x29, 0x78, 0x0a, 0x20, 0x94, 0x94, 0x24,
	0x4c, 0xa1, 0x64, 0x9d, 0xbb, 0xd5, 0x61, 0xfb, 0xd0, 0x7f, 0x2c, 0xb4, 0x49, 0xe9, 0x63, 0x45,
	0xda, 0xb0, 0x5b, 0x18, 0x54, 0x47, 0x5d, 0x2a, 0xa9, 0x09, 0x63, 0xf8, 0x67, 0xf7, 0xe8, 0xd0,
	0x1b, 0xf6, 0xfe, 0xe6, 0xb4, 0x37, 0x92, 0x56, 0x00, 0x1b, 0x00, 0x4c, 0xa8, 0xf1, 0x19, 0x7f,
	0x7a, 0xd0, 0xb7, 0xea, 0x94, 0x96, 0xeb, 0x42, 0x10, 0xde, 0x83, 0x6f, 0x7d, 0xf1, 0x64, 0xd3,
	0xa0, 0xb5, 0x3a, 0x8a, 0x76, 0x49, 0x55, 0x0c, 0xd6, 0xc1, 0x6b, 0xe8, 0x4d, 0xc8, 0x60, 0xb8,
	0x09, 0xfd, 0x6e, 0x8c, 0x76, 0x44, 0x63, 0x9d, 0x87, 0x8b, 0x97, 0xf3, 0x79, 0x61, 0x5e, 0x57,
	0x33, 0x2e, 0xd4, 0x22, 0xa9, 0x89, 0xc4, 0xbd, 0x29, 0x9f, 0xab, 0xa4, 0xfe, 0x11, 0x77, 0xa5,
	0x2d, 0x66, 0x81, 0xeb, 0x5f, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x9f, 0x2c, 0xed, 0x29,
	0x02, 0x00, 0x00,
}
