// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment/v0/flavor.proto

package pdeployment // import "github.com/n0stack/proto.go/deployment/v0"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import v0 "github.com/n0stack/proto.go/provisioning/v0"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Flavor struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version              uint64            `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	LimitCpuMilliCore    uint32            `protobuf:"varint,10,opt,name=limit_cpu_milli_core,json=limitCpuMilliCore" json:"limit_cpu_milli_core,omitempty"`
	LimitMemoryBytes     uint64            `protobuf:"varint,11,opt,name=limit_memory_bytes,json=limitMemoryBytes" json:"limit_memory_bytes,omitempty"`
	LimitStorageBytes    uint64            `protobuf:"varint,12,opt,name=limit_storage_bytes,json=limitStorageBytes" json:"limit_storage_bytes,omitempty"`
	NetworkName          string            `protobuf:"bytes,13,opt,name=network_name,json=networkName" json:"network_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Flavor) Reset()         { *m = Flavor{} }
func (m *Flavor) String() string { return proto.CompactTextString(m) }
func (*Flavor) ProtoMessage()    {}
func (*Flavor) Descriptor() ([]byte, []int) {
	return fileDescriptor_flavor_dde851486c10756e, []int{0}
}
func (m *Flavor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flavor.Unmarshal(m, b)
}
func (m *Flavor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flavor.Marshal(b, m, deterministic)
}
func (dst *Flavor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flavor.Merge(dst, src)
}
func (m *Flavor) XXX_Size() int {
	return xxx_messageInfo_Flavor.Size(m)
}
func (m *Flavor) XXX_DiscardUnknown() {
	xxx_messageInfo_Flavor.DiscardUnknown(m)
}

var xxx_messageInfo_Flavor proto.InternalMessageInfo

func (m *Flavor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Flavor) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Flavor) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Flavor) GetLimitCpuMilliCore() uint32 {
	if m != nil {
		return m.LimitCpuMilliCore
	}
	return 0
}

func (m *Flavor) GetLimitMemoryBytes() uint64 {
	if m != nil {
		return m.LimitMemoryBytes
	}
	return 0
}

func (m *Flavor) GetLimitStorageBytes() uint64 {
	if m != nil {
		return m.LimitStorageBytes
	}
	return 0
}

func (m *Flavor) GetNetworkName() string {
	if m != nil {
		return m.NetworkName
	}
	return ""
}

type ListFlavorsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFlavorsRequest) Reset()         { *m = ListFlavorsRequest{} }
func (m *ListFlavorsRequest) String() string { return proto.CompactTextString(m) }
func (*ListFlavorsRequest) ProtoMessage()    {}
func (*ListFlavorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flavor_dde851486c10756e, []int{1}
}
func (m *ListFlavorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFlavorsRequest.Unmarshal(m, b)
}
func (m *ListFlavorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFlavorsRequest.Marshal(b, m, deterministic)
}
func (dst *ListFlavorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFlavorsRequest.Merge(dst, src)
}
func (m *ListFlavorsRequest) XXX_Size() int {
	return xxx_messageInfo_ListFlavorsRequest.Size(m)
}
func (m *ListFlavorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFlavorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFlavorsRequest proto.InternalMessageInfo

type ListFlavorsResponse struct {
	Flavors              []*Flavor `protobuf:"bytes,1,rep,name=flavors" json:"flavors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListFlavorsResponse) Reset()         { *m = ListFlavorsResponse{} }
func (m *ListFlavorsResponse) String() string { return proto.CompactTextString(m) }
func (*ListFlavorsResponse) ProtoMessage()    {}
func (*ListFlavorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flavor_dde851486c10756e, []int{2}
}
func (m *ListFlavorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFlavorsResponse.Unmarshal(m, b)
}
func (m *ListFlavorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFlavorsResponse.Marshal(b, m, deterministic)
}
func (dst *ListFlavorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFlavorsResponse.Merge(dst, src)
}
func (m *ListFlavorsResponse) XXX_Size() int {
	return xxx_messageInfo_ListFlavorsResponse.Size(m)
}
func (m *ListFlavorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFlavorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFlavorsResponse proto.InternalMessageInfo

func (m *ListFlavorsResponse) GetFlavors() []*Flavor {
	if m != nil {
		return m.Flavors
	}
	return nil
}

type GetFlavorRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlavorRequest) Reset()         { *m = GetFlavorRequest{} }
func (m *GetFlavorRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlavorRequest) ProtoMessage()    {}
func (*GetFlavorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flavor_dde851486c10756e, []int{3}
}
func (m *GetFlavorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlavorRequest.Unmarshal(m, b)
}
func (m *GetFlavorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlavorRequest.Marshal(b, m, deterministic)
}
func (dst *GetFlavorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlavorRequest.Merge(dst, src)
}
func (m *GetFlavorRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlavorRequest.Size(m)
}
func (m *GetFlavorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlavorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlavorRequest proto.InternalMessageInfo

func (m *GetFlavorRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ApplyFlavorRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version              uint64            `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	LimitCpuMilliCore    uint32            `protobuf:"varint,10,opt,name=limit_cpu_milli_core,json=limitCpuMilliCore" json:"limit_cpu_milli_core,omitempty"`
	LimitMemoryBytes     uint64            `protobuf:"varint,11,opt,name=limit_memory_bytes,json=limitMemoryBytes" json:"limit_memory_bytes,omitempty"`
	NetworkName          string            `protobuf:"bytes,12,opt,name=network_name,json=networkName" json:"network_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ApplyFlavorRequest) Reset()         { *m = ApplyFlavorRequest{} }
func (m *ApplyFlavorRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyFlavorRequest) ProtoMessage()    {}
func (*ApplyFlavorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flavor_dde851486c10756e, []int{4}
}
func (m *ApplyFlavorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyFlavorRequest.Unmarshal(m, b)
}
func (m *ApplyFlavorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyFlavorRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyFlavorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyFlavorRequest.Merge(dst, src)
}
func (m *ApplyFlavorRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyFlavorRequest.Size(m)
}
func (m *ApplyFlavorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyFlavorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyFlavorRequest proto.InternalMessageInfo

func (m *ApplyFlavorRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplyFlavorRequest) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *ApplyFlavorRequest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ApplyFlavorRequest) GetLimitCpuMilliCore() uint32 {
	if m != nil {
		return m.LimitCpuMilliCore
	}
	return 0
}

func (m *ApplyFlavorRequest) GetLimitMemoryBytes() uint64 {
	if m != nil {
		return m.LimitMemoryBytes
	}
	return 0
}

func (m *ApplyFlavorRequest) GetNetworkName() string {
	if m != nil {
		return m.NetworkName
	}
	return ""
}

type DeleteFlavorRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFlavorRequest) Reset()         { *m = DeleteFlavorRequest{} }
func (m *DeleteFlavorRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFlavorRequest) ProtoMessage()    {}
func (*DeleteFlavorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flavor_dde851486c10756e, []int{5}
}
func (m *DeleteFlavorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFlavorRequest.Unmarshal(m, b)
}
func (m *DeleteFlavorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFlavorRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteFlavorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFlavorRequest.Merge(dst, src)
}
func (m *DeleteFlavorRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFlavorRequest.Size(m)
}
func (m *DeleteFlavorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFlavorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFlavorRequest proto.InternalMessageInfo

func (m *DeleteFlavorRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GenerateVirtualMachineRequest struct {
	FlavorName           string            `protobuf:"bytes,1,opt,name=flavor_name,json=flavorName" json:"flavor_name,omitempty"`
	VirtualMachineName   string            `protobuf:"bytes,2,opt,name=virtual_machine_name,json=virtualMachineName" json:"virtual_machine_name,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestCpuMilliCore  uint32            `protobuf:"varint,4,opt,name=request_cpu_milli_core,json=requestCpuMilliCore" json:"request_cpu_milli_core,omitempty"`
	RequestMemoryBytes   uint64            `protobuf:"varint,5,opt,name=request_memory_bytes,json=requestMemoryBytes" json:"request_memory_bytes,omitempty"`
	RequestStorageBytes  uint64            `protobuf:"varint,6,opt,name=request_storage_bytes,json=requestStorageBytes" json:"request_storage_bytes,omitempty"`
	ImageName            string            `protobuf:"bytes,7,opt,name=image_name,json=imageName" json:"image_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenerateVirtualMachineRequest) Reset()         { *m = GenerateVirtualMachineRequest{} }
func (m *GenerateVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateVirtualMachineRequest) ProtoMessage()    {}
func (*GenerateVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flavor_dde851486c10756e, []int{6}
}
func (m *GenerateVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateVirtualMachineRequest.Unmarshal(m, b)
}
func (m *GenerateVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateVirtualMachineRequest.Merge(dst, src)
}
func (m *GenerateVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateVirtualMachineRequest.Size(m)
}
func (m *GenerateVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateVirtualMachineRequest proto.InternalMessageInfo

func (m *GenerateVirtualMachineRequest) GetFlavorName() string {
	if m != nil {
		return m.FlavorName
	}
	return ""
}

func (m *GenerateVirtualMachineRequest) GetVirtualMachineName() string {
	if m != nil {
		return m.VirtualMachineName
	}
	return ""
}

func (m *GenerateVirtualMachineRequest) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *GenerateVirtualMachineRequest) GetRequestCpuMilliCore() uint32 {
	if m != nil {
		return m.RequestCpuMilliCore
	}
	return 0
}

func (m *GenerateVirtualMachineRequest) GetRequestMemoryBytes() uint64 {
	if m != nil {
		return m.RequestMemoryBytes
	}
	return 0
}

func (m *GenerateVirtualMachineRequest) GetRequestStorageBytes() uint64 {
	if m != nil {
		return m.RequestStorageBytes
	}
	return 0
}

func (m *GenerateVirtualMachineRequest) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func init() {
	proto.RegisterType((*Flavor)(nil), "n0stack.deployment.Flavor")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.deployment.Flavor.AnnotationsEntry")
	proto.RegisterType((*ListFlavorsRequest)(nil), "n0stack.deployment.ListFlavorsRequest")
	proto.RegisterType((*ListFlavorsResponse)(nil), "n0stack.deployment.ListFlavorsResponse")
	proto.RegisterType((*GetFlavorRequest)(nil), "n0stack.deployment.GetFlavorRequest")
	proto.RegisterType((*ApplyFlavorRequest)(nil), "n0stack.deployment.ApplyFlavorRequest")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.deployment.ApplyFlavorRequest.AnnotationsEntry")
	proto.RegisterType((*DeleteFlavorRequest)(nil), "n0stack.deployment.DeleteFlavorRequest")
	proto.RegisterType((*GenerateVirtualMachineRequest)(nil), "n0stack.deployment.GenerateVirtualMachineRequest")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.deployment.GenerateVirtualMachineRequest.AnnotationsEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FlavorService service

type FlavorServiceClient interface {
	ListFlavors(ctx context.Context, in *ListFlavorsRequest, opts ...grpc.CallOption) (*ListFlavorsResponse, error)
	GetFlavor(ctx context.Context, in *GetFlavorRequest, opts ...grpc.CallOption) (*Flavor, error)
	ApplyFlavor(ctx context.Context, in *ApplyFlavorRequest, opts ...grpc.CallOption) (*Flavor, error)
	DeleteFlavor(ctx context.Context, in *DeleteFlavorRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GenerateVirtualMachine(ctx context.Context, in *GenerateVirtualMachineRequest, opts ...grpc.CallOption) (*v0.VirtualMachine, error)
}

type flavorServiceClient struct {
	cc *grpc.ClientConn
}

func NewFlavorServiceClient(cc *grpc.ClientConn) FlavorServiceClient {
	return &flavorServiceClient{cc}
}

func (c *flavorServiceClient) ListFlavors(ctx context.Context, in *ListFlavorsRequest, opts ...grpc.CallOption) (*ListFlavorsResponse, error) {
	out := new(ListFlavorsResponse)
	err := grpc.Invoke(ctx, "/n0stack.deployment.FlavorService/ListFlavors", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flavorServiceClient) GetFlavor(ctx context.Context, in *GetFlavorRequest, opts ...grpc.CallOption) (*Flavor, error) {
	out := new(Flavor)
	err := grpc.Invoke(ctx, "/n0stack.deployment.FlavorService/GetFlavor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flavorServiceClient) ApplyFlavor(ctx context.Context, in *ApplyFlavorRequest, opts ...grpc.CallOption) (*Flavor, error) {
	out := new(Flavor)
	err := grpc.Invoke(ctx, "/n0stack.deployment.FlavorService/ApplyFlavor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flavorServiceClient) DeleteFlavor(ctx context.Context, in *DeleteFlavorRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/n0stack.deployment.FlavorService/DeleteFlavor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flavorServiceClient) GenerateVirtualMachine(ctx context.Context, in *GenerateVirtualMachineRequest, opts ...grpc.CallOption) (*v0.VirtualMachine, error) {
	out := new(v0.VirtualMachine)
	err := grpc.Invoke(ctx, "/n0stack.deployment.FlavorService/GenerateVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FlavorService service

type FlavorServiceServer interface {
	ListFlavors(context.Context, *ListFlavorsRequest) (*ListFlavorsResponse, error)
	GetFlavor(context.Context, *GetFlavorRequest) (*Flavor, error)
	ApplyFlavor(context.Context, *ApplyFlavorRequest) (*Flavor, error)
	DeleteFlavor(context.Context, *DeleteFlavorRequest) (*empty.Empty, error)
	GenerateVirtualMachine(context.Context, *GenerateVirtualMachineRequest) (*v0.VirtualMachine, error)
}

func RegisterFlavorServiceServer(s *grpc.Server, srv FlavorServiceServer) {
	s.RegisterService(&_FlavorService_serviceDesc, srv)
}

func _FlavorService_ListFlavors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlavorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).ListFlavors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.FlavorService/ListFlavors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).ListFlavors(ctx, req.(*ListFlavorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlavorService_GetFlavor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlavorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).GetFlavor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.FlavorService/GetFlavor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).GetFlavor(ctx, req.(*GetFlavorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlavorService_ApplyFlavor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyFlavorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).ApplyFlavor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.FlavorService/ApplyFlavor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).ApplyFlavor(ctx, req.(*ApplyFlavorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlavorService_DeleteFlavor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFlavorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).DeleteFlavor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.FlavorService/DeleteFlavor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).DeleteFlavor(ctx, req.(*DeleteFlavorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlavorService_GenerateVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).GenerateVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.FlavorService/GenerateVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).GenerateVirtualMachine(ctx, req.(*GenerateVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlavorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "n0stack.deployment.FlavorService",
	HandlerType: (*FlavorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFlavors",
			Handler:    _FlavorService_ListFlavors_Handler,
		},
		{
			MethodName: "GetFlavor",
			Handler:    _FlavorService_GetFlavor_Handler,
		},
		{
			MethodName: "ApplyFlavor",
			Handler:    _FlavorService_ApplyFlavor_Handler,
		},
		{
			MethodName: "DeleteFlavor",
			Handler:    _FlavorService_DeleteFlavor_Handler,
		},
		{
			MethodName: "GenerateVirtualMachine",
			Handler:    _FlavorService_GenerateVirtualMachine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployment/v0/flavor.proto",
}

func init() { proto.RegisterFile("deployment/v0/flavor.proto", fileDescriptor_flavor_dde851486c10756e) }

var fileDescriptor_flavor_dde851486c10756e = []byte{
	// 691 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xce, 0x4f, 0x7f, 0xd4, 0x49, 0x2a, 0x85, 0x4d, 0xa8, 0x2c, 0xa3, 0x8a, 0x60, 0x41, 0x09,
	0x02, 0x39, 0xa1, 0x05, 0x15, 0x81, 0x84, 0xd4, 0x96, 0xd2, 0x03, 0x04, 0x44, 0x2a, 0x21, 0xc1,
	0xc5, 0x38, 0xe9, 0x34, 0x5d, 0xd5, 0xf6, 0x9a, 0xf5, 0xda, 0xc8, 0xaf, 0xc9, 0x0b, 0xf4, 0x31,
	0xb8, 0x22, 0xef, 0xda, 0xc4, 0x4e, 0x4c, 0x23, 0xa4, 0x1e, 0xb8, 0x79, 0x67, 0xbe, 0x99, 0x1d,
	0xcf, 0x37, 0xdf, 0x0e, 0xe8, 0x67, 0xe8, 0x3b, 0x2c, 0x76, 0xd1, 0x13, 0xfd, 0x68, 0xd0, 0x3f,
	0x77, 0xec, 0x88, 0x71, 0xd3, 0xe7, 0x4c, 0x30, 0x42, 0xbc, 0x41, 0x20, 0xec, 0xc9, 0xa5, 0x39,
	0xc3, 0xe8, 0x77, 0xa6, 0x8c, 0x4d, 0x1d, 0xec, 0x4b, 0xc4, 0x38, 0x3c, 0xef, 0xa3, 0xeb, 0x8b,
	0x58, 0x05, 0xe8, 0x0f, 0x7c, 0xce, 0x22, 0x1a, 0x50, 0xe6, 0x51, 0x6f, 0x9a, 0xa4, 0x8b, 0x28,
	0x17, 0xa1, 0xed, 0x58, 0xae, 0x3d, 0xb9, 0xa0, 0x1e, 0x2a, 0x98, 0xf1, 0xab, 0x06, 0x6b, 0x6f,
	0xe5, 0x45, 0x84, 0xc0, 0x8a, 0x67, 0xbb, 0xa8, 0x55, 0xbb, 0xd5, 0xde, 0xc6, 0x48, 0x7e, 0x93,
	0x21, 0x34, 0x6c, 0xcf, 0x63, 0xc2, 0x16, 0x94, 0x79, 0x81, 0x56, 0xef, 0xd6, 0x7b, 0x8d, 0xdd,
	0xc7, 0xe6, 0x62, 0x31, 0xa6, 0x4a, 0x62, 0x1e, 0xcc, 0xd0, 0xc7, 0x9e, 0xe0, 0xf1, 0x28, 0x1f,
	0x4f, 0x34, 0x58, 0x8f, 0x90, 0x27, 0x45, 0x69, 0xab, 0xdd, 0x6a, 0x6f, 0x65, 0x94, 0x1d, 0x49,
	0x1f, 0x3a, 0x0e, 0x75, 0xa9, 0xb0, 0x26, 0x7e, 0x68, 0xb9, 0xd4, 0x71, 0xa8, 0x35, 0x61, 0x1c,
	0x35, 0xe8, 0x56, 0x7b, 0x9b, 0xa3, 0x5b, 0xd2, 0x77, 0xe4, 0x87, 0xc3, 0xc4, 0x73, 0xc4, 0x38,
	0x92, 0x27, 0x40, 0x54, 0x80, 0x8b, 0x2e, 0xe3, 0xb1, 0x35, 0x8e, 0x05, 0x06, 0x5a, 0x43, 0x66,
	0x6d, 0x49, 0xcf, 0x50, 0x3a, 0x0e, 0x13, 0x3b, 0x31, 0xa1, 0xad, 0xd0, 0x81, 0x60, 0xdc, 0x9e,
	0x62, 0x0a, 0x6f, 0x4a, 0xb8, 0xca, 0x7e, 0xaa, 0x3c, 0x0a, 0x7f, 0x0f, 0x9a, 0x1e, 0x8a, 0x1f,
	0x8c, 0x5f, 0x5a, 0xb2, 0x27, 0x9b, 0xb2, 0x27, 0x8d, 0xd4, 0xf6, 0xc1, 0x76, 0x51, 0x7f, 0x0d,
	0xad, 0xf9, 0x9f, 0x25, 0x2d, 0xa8, 0x5f, 0x62, 0x9c, 0x76, 0x30, 0xf9, 0x24, 0x1d, 0x58, 0x8d,
	0x6c, 0x27, 0x44, 0xad, 0x26, 0x6d, 0xea, 0xf0, 0xb2, 0xf6, 0xa2, 0x6a, 0x74, 0x80, 0xbc, 0xa7,
	0x81, 0x50, 0x7d, 0x0b, 0x46, 0xf8, 0x3d, 0xc4, 0x40, 0x18, 0xef, 0xa0, 0x5d, 0xb0, 0x06, 0x3e,
	0xf3, 0x02, 0x24, 0xcf, 0x60, 0x5d, 0x8d, 0x43, 0xa0, 0x55, 0x25, 0x07, 0xfa, 0xdf, 0x39, 0x18,
	0x65, 0x50, 0x63, 0x07, 0x5a, 0x27, 0x98, 0xe6, 0x4a, 0x2f, 0x28, 0x63, 0xd9, 0xb8, 0xaa, 0x01,
	0x39, 0xf0, 0x7d, 0x27, 0x5e, 0x0a, 0x25, 0x5f, 0xca, 0x06, 0x62, 0xbf, 0xac, 0x98, 0xc5, 0x84,
	0xff, 0xeb, 0x70, 0xcc, 0x93, 0xdd, 0xbc, 0x79, 0xb2, 0x1f, 0x41, 0xfb, 0x0d, 0x3a, 0x28, 0x70,
	0x39, 0x19, 0x3f, 0xeb, 0xb0, 0x7d, 0x82, 0x1e, 0x72, 0x5b, 0xe0, 0x67, 0xa5, 0xd9, 0xa1, 0x92,
	0x6c, 0x16, 0x75, 0x17, 0x1a, 0x8a, 0x61, 0x2b, 0x17, 0x0c, 0xca, 0x94, 0x54, 0x4b, 0x06, 0xd0,
	0x99, 0x53, 0xbb, 0x42, 0xaa, 0xb2, 0x48, 0x54, 0xc8, 0x2a, 0x23, 0xce, 0xca, 0x68, 0x3d, 0x2c,
	0xa3, 0xf5, 0xda, 0xd2, 0x96, 0x30, 0xbc, 0x07, 0x5b, 0x5c, 0x01, 0xe7, 0x99, 0x5c, 0x91, 0x4c,
	0xb6, 0x53, 0x6f, 0x81, 0xcb, 0x01, 0x74, 0xb2, 0xa0, 0x02, 0x9b, 0x6a, 0x46, 0x48, 0xea, 0xcb,
	0xf3, 0xb9, 0x0b, 0xb7, 0xb3, 0x88, 0xa2, 0xdc, 0xd7, 0x64, 0x48, 0x76, 0x4b, 0x41, 0xf0, 0xdb,
	0x00, 0xd4, 0x4d, 0x90, 0xb2, 0x51, 0xeb, 0xb2, 0x51, 0x1b, 0xd2, 0x72, 0x13, 0xfc, 0xef, 0x5e,
	0xd5, 0x61, 0x53, 0x51, 0x7f, 0x8a, 0x3c, 0xa2, 0x13, 0x24, 0xdf, 0xa0, 0x91, 0x13, 0x3a, 0xd9,
	0x29, 0xeb, 0xf5, 0xe2, 0xfb, 0xa0, 0x3f, 0x5c, 0x8a, 0x53, 0x2f, 0x86, 0x51, 0x21, 0x1f, 0x61,
	0xe3, 0x8f, 0xfa, 0xc9, 0xfd, 0x72, 0x2e, 0x8b, 0x8f, 0x83, 0x7e, 0xcd, 0xab, 0x62, 0x54, 0xc8,
	0x29, 0x34, 0x72, 0xa2, 0x2e, 0x2f, 0x79, 0x51, 0xf5, 0x4b, 0x92, 0x7e, 0x82, 0x66, 0x5e, 0x19,
	0xa4, 0xf4, 0x07, 0x4b, 0xb4, 0xa3, 0x6f, 0x99, 0x6a, 0xfd, 0x99, 0xd9, 0xfa, 0x33, 0x8f, 0x93,
	0xf5, 0x67, 0x54, 0x48, 0x00, 0x5b, 0xe5, 0x53, 0x4a, 0x9e, 0xfe, 0xf3, 0x44, 0xeb, 0xb3, 0xc6,
	0xe5, 0x17, 0xaa, 0x59, 0x04, 0x1b, 0x95, 0xc3, 0xfd, 0xaf, 0xcf, 0xa7, 0x54, 0x5c, 0x84, 0x63,
	0x73, 0xc2, 0xdc, 0x7e, 0x1a, 0xa3, 0x56, 0xb3, 0x39, 0x65, 0xfd, 0xc2, 0x6a, 0x7f, 0xe5, 0xcf,
	0x8e, 0xe3, 0x35, 0x89, 0xd9, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x37, 0x1d, 0xa0, 0x8e, 0xfe,
	0x07, 0x00, 0x00,
}
