// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment/v0/image.proto

package pdeployment // import "github.com/n0stack/proto.go/deployment/v0"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import v0 "github.com/n0stack/proto.go/v0"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Image struct {
	Metadata *v0.Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	// ImageSpec spec = 2;
	Status               *ImageStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_b24f33cd11945124, []int{0}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetMetadata() *v0.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Image) GetStatus() *ImageStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ImageStatus struct {
	RegisteredBlockStorageNames map[string]*timestamp.Timestamp `protobuf:"bytes,1,rep,name=registered_block_storage_names,json=registeredBlockStorageNames" json:"registered_block_storage_names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags                        map[string]string               `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral        struct{}                        `json:"-"`
	XXX_unrecognized            []byte                          `json:"-"`
	XXX_sizecache               int32                           `json:"-"`
}

func (m *ImageStatus) Reset()         { *m = ImageStatus{} }
func (m *ImageStatus) String() string { return proto.CompactTextString(m) }
func (*ImageStatus) ProtoMessage()    {}
func (*ImageStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_b24f33cd11945124, []int{1}
}
func (m *ImageStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageStatus.Unmarshal(m, b)
}
func (m *ImageStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageStatus.Marshal(b, m, deterministic)
}
func (dst *ImageStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageStatus.Merge(dst, src)
}
func (m *ImageStatus) XXX_Size() int {
	return xxx_messageInfo_ImageStatus.Size(m)
}
func (m *ImageStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ImageStatus proto.InternalMessageInfo

func (m *ImageStatus) GetRegisteredBlockStorageNames() map[string]*timestamp.Timestamp {
	if m != nil {
		return m.RegisteredBlockStorageNames
	}
	return nil
}

func (m *ImageStatus) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ListImagesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListImagesRequest) Reset()         { *m = ListImagesRequest{} }
func (m *ListImagesRequest) String() string { return proto.CompactTextString(m) }
func (*ListImagesRequest) ProtoMessage()    {}
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_b24f33cd11945124, []int{2}
}
func (m *ListImagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListImagesRequest.Unmarshal(m, b)
}
func (m *ListImagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListImagesRequest.Marshal(b, m, deterministic)
}
func (dst *ListImagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListImagesRequest.Merge(dst, src)
}
func (m *ListImagesRequest) XXX_Size() int {
	return xxx_messageInfo_ListImagesRequest.Size(m)
}
func (m *ListImagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListImagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListImagesRequest proto.InternalMessageInfo

type ListImagesResponse struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=Images" json:"Images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListImagesResponse) Reset()         { *m = ListImagesResponse{} }
func (m *ListImagesResponse) String() string { return proto.CompactTextString(m) }
func (*ListImagesResponse) ProtoMessage()    {}
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_b24f33cd11945124, []int{3}
}
func (m *ListImagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListImagesResponse.Unmarshal(m, b)
}
func (m *ListImagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListImagesResponse.Marshal(b, m, deterministic)
}
func (dst *ListImagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListImagesResponse.Merge(dst, src)
}
func (m *ListImagesResponse) XXX_Size() int {
	return xxx_messageInfo_ListImagesResponse.Size(m)
}
func (m *ListImagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListImagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListImagesResponse proto.InternalMessageInfo

func (m *ListImagesResponse) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type GetImageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetImageRequest) Reset()         { *m = GetImageRequest{} }
func (m *GetImageRequest) String() string { return proto.CompactTextString(m) }
func (*GetImageRequest) ProtoMessage()    {}
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_b24f33cd11945124, []int{4}
}
func (m *GetImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetImageRequest.Unmarshal(m, b)
}
func (m *GetImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetImageRequest.Marshal(b, m, deterministic)
}
func (dst *GetImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetImageRequest.Merge(dst, src)
}
func (m *GetImageRequest) XXX_Size() int {
	return xxx_messageInfo_GetImageRequest.Size(m)
}
func (m *GetImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetImageRequest proto.InternalMessageInfo

func (m *GetImageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ApplyImageRequest struct {
	Metadata             *v0.Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ApplyImageRequest) Reset()         { *m = ApplyImageRequest{} }
func (m *ApplyImageRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyImageRequest) ProtoMessage()    {}
func (*ApplyImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_b24f33cd11945124, []int{5}
}
func (m *ApplyImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyImageRequest.Unmarshal(m, b)
}
func (m *ApplyImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyImageRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyImageRequest.Merge(dst, src)
}
func (m *ApplyImageRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyImageRequest.Size(m)
}
func (m *ApplyImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyImageRequest proto.InternalMessageInfo

func (m *ApplyImageRequest) GetMetadata() *v0.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type DeleteImageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteImageRequest) Reset()         { *m = DeleteImageRequest{} }
func (m *DeleteImageRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteImageRequest) ProtoMessage()    {}
func (*DeleteImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_b24f33cd11945124, []int{6}
}
func (m *DeleteImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteImageRequest.Unmarshal(m, b)
}
func (m *DeleteImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteImageRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteImageRequest.Merge(dst, src)
}
func (m *DeleteImageRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteImageRequest.Size(m)
}
func (m *DeleteImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteImageRequest proto.InternalMessageInfo

func (m *DeleteImageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ImportBlockStorageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	BlockStorageName     string   `protobuf:"bytes,2,opt,name=block_storage_name,json=blockStorageName" json:"block_storage_name,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportBlockStorageRequest) Reset()         { *m = ImportBlockStorageRequest{} }
func (m *ImportBlockStorageRequest) String() string { return proto.CompactTextString(m) }
func (*ImportBlockStorageRequest) ProtoMessage()    {}
func (*ImportBlockStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_b24f33cd11945124, []int{7}
}
func (m *ImportBlockStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportBlockStorageRequest.Unmarshal(m, b)
}
func (m *ImportBlockStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportBlockStorageRequest.Marshal(b, m, deterministic)
}
func (dst *ImportBlockStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportBlockStorageRequest.Merge(dst, src)
}
func (m *ImportBlockStorageRequest) XXX_Size() int {
	return xxx_messageInfo_ImportBlockStorageRequest.Size(m)
}
func (m *ImportBlockStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportBlockStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportBlockStorageRequest proto.InternalMessageInfo

func (m *ImportBlockStorageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImportBlockStorageRequest) GetBlockStorageName() string {
	if m != nil {
		return m.BlockStorageName
	}
	return ""
}

func (m *ImportBlockStorageRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type TagImageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	BlockStorageName     string   `protobuf:"bytes,2,opt,name=block_storage_name,json=blockStorageName" json:"block_storage_name,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagImageRequest) Reset()         { *m = TagImageRequest{} }
func (m *TagImageRequest) String() string { return proto.CompactTextString(m) }
func (*TagImageRequest) ProtoMessage()    {}
func (*TagImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_b24f33cd11945124, []int{8}
}
func (m *TagImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagImageRequest.Unmarshal(m, b)
}
func (m *TagImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagImageRequest.Marshal(b, m, deterministic)
}
func (dst *TagImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagImageRequest.Merge(dst, src)
}
func (m *TagImageRequest) XXX_Size() int {
	return xxx_messageInfo_TagImageRequest.Size(m)
}
func (m *TagImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagImageRequest proto.InternalMessageInfo

func (m *TagImageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TagImageRequest) GetBlockStorageName() string {
	if m != nil {
		return m.BlockStorageName
	}
	return ""
}

func (m *TagImageRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type UntagImageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UntagImageRequest) Reset()         { *m = UntagImageRequest{} }
func (m *UntagImageRequest) String() string { return proto.CompactTextString(m) }
func (*UntagImageRequest) ProtoMessage()    {}
func (*UntagImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_b24f33cd11945124, []int{9}
}
func (m *UntagImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UntagImageRequest.Unmarshal(m, b)
}
func (m *UntagImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UntagImageRequest.Marshal(b, m, deterministic)
}
func (dst *UntagImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UntagImageRequest.Merge(dst, src)
}
func (m *UntagImageRequest) XXX_Size() int {
	return xxx_messageInfo_UntagImageRequest.Size(m)
}
func (m *UntagImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UntagImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UntagImageRequest proto.InternalMessageInfo

func (m *UntagImageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UntagImageRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func init() {
	proto.RegisterType((*Image)(nil), "n0stack.deployment.Image")
	proto.RegisterType((*ImageStatus)(nil), "n0stack.deployment.ImageStatus")
	proto.RegisterMapType((map[string]*timestamp.Timestamp)(nil), "n0stack.deployment.ImageStatus.RegisteredBlockStorageNamesEntry")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.deployment.ImageStatus.TagsEntry")
	proto.RegisterType((*ListImagesRequest)(nil), "n0stack.deployment.ListImagesRequest")
	proto.RegisterType((*ListImagesResponse)(nil), "n0stack.deployment.ListImagesResponse")
	proto.RegisterType((*GetImageRequest)(nil), "n0stack.deployment.GetImageRequest")
	proto.RegisterType((*ApplyImageRequest)(nil), "n0stack.deployment.ApplyImageRequest")
	proto.RegisterType((*DeleteImageRequest)(nil), "n0stack.deployment.DeleteImageRequest")
	proto.RegisterType((*ImportBlockStorageRequest)(nil), "n0stack.deployment.ImportBlockStorageRequest")
	proto.RegisterType((*TagImageRequest)(nil), "n0stack.deployment.TagImageRequest")
	proto.RegisterType((*UntagImageRequest)(nil), "n0stack.deployment.UntagImageRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ImageService service

type ImageServiceClient interface {
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*Image, error)
	ApplyImage(ctx context.Context, in *ApplyImageRequest, opts ...grpc.CallOption) (*Image, error)
	DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RegisterBlockStorage(ctx context.Context, in *ImportBlockStorageRequest, opts ...grpc.CallOption) (*Image, error)
	TagImage(ctx context.Context, in *TagImageRequest, opts ...grpc.CallOption) (*Image, error)
	UntagImage(ctx context.Context, in *UntagImageRequest, opts ...grpc.CallOption) (*Image, error)
}

type imageServiceClient struct {
	cc *grpc.ClientConn
}

func NewImageServiceClient(cc *grpc.ClientConn) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	out := new(ListImagesResponse)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/ListImages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/GetImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) ApplyImage(ctx context.Context, in *ApplyImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/ApplyImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/DeleteImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) RegisterBlockStorage(ctx context.Context, in *ImportBlockStorageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/RegisterBlockStorage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) TagImage(ctx context.Context, in *TagImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/TagImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) UntagImage(ctx context.Context, in *UntagImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/UntagImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ImageService service

type ImageServiceServer interface {
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	GetImage(context.Context, *GetImageRequest) (*Image, error)
	ApplyImage(context.Context, *ApplyImageRequest) (*Image, error)
	DeleteImage(context.Context, *DeleteImageRequest) (*empty.Empty, error)
	RegisterBlockStorage(context.Context, *ImportBlockStorageRequest) (*Image, error)
	TagImage(context.Context, *TagImageRequest) (*Image, error)
	UntagImage(context.Context, *UntagImageRequest) (*Image, error)
}

func RegisterImageServiceServer(s *grpc.Server, srv ImageServiceServer) {
	s.RegisterService(&_ImageService_serviceDesc, srv)
}

func _ImageService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/ListImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/GetImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).GetImage(ctx, req.(*GetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_ApplyImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).ApplyImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/ApplyImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).ApplyImage(ctx, req.(*ApplyImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/DeleteImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).DeleteImage(ctx, req.(*DeleteImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_RegisterBlockStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportBlockStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).RegisterBlockStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/RegisterBlockStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).RegisterBlockStorage(ctx, req.(*ImportBlockStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_TagImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).TagImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/TagImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).TagImage(ctx, req.(*TagImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_UntagImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntagImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).UntagImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/UntagImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).UntagImage(ctx, req.(*UntagImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "n0stack.deployment.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _ImageService_ListImages_Handler,
		},
		{
			MethodName: "GetImage",
			Handler:    _ImageService_GetImage_Handler,
		},
		{
			MethodName: "ApplyImage",
			Handler:    _ImageService_ApplyImage_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _ImageService_DeleteImage_Handler,
		},
		{
			MethodName: "RegisterBlockStorage",
			Handler:    _ImageService_RegisterBlockStorage_Handler,
		},
		{
			MethodName: "TagImage",
			Handler:    _ImageService_TagImage_Handler,
		},
		{
			MethodName: "UntagImage",
			Handler:    _ImageService_UntagImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployment/v0/image.proto",
}

func init() { proto.RegisterFile("deployment/v0/image.proto", fileDescriptor_image_b24f33cd11945124) }

var fileDescriptor_image_b24f33cd11945124 = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x7f, 0x6b, 0xda, 0x40,
	0x18, 0xc7, 0xab, 0x69, 0x8b, 0x3e, 0x0e, 0xaa, 0xb7, 0x32, 0x34, 0x85, 0x55, 0x32, 0x3a, 0x1c,
	0xac, 0x89, 0x73, 0x0c, 0xf7, 0x83, 0xc1, 0x26, 0x2b, 0xa5, 0xe0, 0x7e, 0x90, 0xba, 0x7f, 0x06,
	0x43, 0x2e, 0x7a, 0xbb, 0x65, 0x26, 0xb9, 0x34, 0x77, 0x0a, 0xbe, 0x80, 0xbd, 0xd1, 0xbd, 0x8b,
	0xfd, 0x37, 0x72, 0x49, 0x34, 0x35, 0xd1, 0x6c, 0xb0, 0xff, 0xce, 0xbb, 0xef, 0x7d, 0xbf, 0x4f,
	0x9e, 0xe7, 0x63, 0x02, 0xad, 0x29, 0xf1, 0x1d, 0xb6, 0x74, 0x89, 0x27, 0x8c, 0x45, 0xd7, 0xb0,
	0x5d, 0x4c, 0x89, 0xee, 0x07, 0x4c, 0x30, 0x84, 0xbc, 0x2e, 0x17, 0x78, 0x32, 0xd3, 0xd7, 0x12,
	0xf5, 0x84, 0x32, 0x46, 0x1d, 0x62, 0x48, 0x85, 0x35, 0xff, 0x66, 0x10, 0xd7, 0x17, 0xcb, 0xe8,
	0x82, 0x7a, 0xba, 0x79, 0x28, 0x6c, 0x97, 0x70, 0x81, 0x5d, 0x3f, 0x16, 0x34, 0x16, 0x5d, 0xc3,
	0x25, 0x02, 0x4f, 0xb1, 0xc0, 0xd1, 0x96, 0xc6, 0xe0, 0xe0, 0x2a, 0xcc, 0x44, 0xe7, 0x50, 0x49,
	0x8e, 0x9a, 0xa5, 0x76, 0xa9, 0x53, 0xeb, 0x35, 0xf4, 0xa4, 0x80, 0xf7, 0xf1, 0x81, 0xb9, 0x92,
	0xa0, 0x3e, 0x1c, 0x72, 0x81, 0xc5, 0x9c, 0x37, 0x15, 0x29, 0x3e, 0xd5, 0xb3, 0xd5, 0xea, 0xd2,
	0xf9, 0x5a, 0xca, 0xcc, 0x58, 0xae, 0xfd, 0x2e, 0x43, 0x2d, 0xb5, 0x8f, 0x7e, 0x96, 0xe0, 0x7e,
	0x40, 0xa8, 0xcd, 0x05, 0x09, 0xc8, 0x74, 0x6c, 0x39, 0x6c, 0x32, 0x1b, 0x73, 0xc1, 0x02, 0x4c,
	0xc9, 0xd8, 0xc3, 0x2e, 0xe1, 0xcd, 0x52, 0x5b, 0xe9, 0xd4, 0x7a, 0x6f, 0x0a, 0x12, 0x74, 0x73,
	0xe5, 0x32, 0x08, 0x4d, 0xae, 0x23, 0x8f, 0x0f, 0xa1, 0xc5, 0x85, 0x27, 0x82, 0xa5, 0x79, 0x12,
	0x6c, 0x57, 0xa0, 0xd7, 0xb0, 0x2f, 0x30, 0xe5, 0xcd, 0xb2, 0x0c, 0x7b, 0x54, 0x14, 0x36, 0xc2,
	0x34, 0x76, 0x95, 0xd7, 0xd4, 0x1f, 0xd0, 0x2e, 0xca, 0x47, 0x75, 0x50, 0x66, 0x64, 0x29, 0xbb,
	0x5b, 0x35, 0xc3, 0x25, 0xea, 0xc2, 0xc1, 0x02, 0x3b, 0x73, 0xd2, 0x2c, 0xcb, 0x26, 0xaa, 0x7a,
	0x34, 0x41, 0x3d, 0x99, 0xa0, 0x3e, 0x4a, 0x26, 0x68, 0x46, 0xc2, 0x97, 0xe5, 0xe7, 0x25, 0xb5,
	0x0f, 0xd5, 0x55, 0x7c, 0x8e, 0xe9, 0x71, 0xda, 0xb4, 0x9a, 0xba, 0xa8, 0xdd, 0x85, 0xc6, 0xd0,
	0xe6, 0x42, 0x3e, 0x07, 0x37, 0xc9, 0xcd, 0x9c, 0x70, 0xa1, 0x5d, 0x02, 0x4a, 0x6f, 0x72, 0x9f,
	0x79, 0x9c, 0xa0, 0x27, 0x70, 0x18, 0xed, 0xc4, 0xdd, 0x6f, 0x6d, 0x6d, 0x88, 0x19, 0x0b, 0xb5,
	0x33, 0x38, 0xba, 0x24, 0x91, 0x4f, 0xec, 0x8d, 0x10, 0xec, 0x87, 0x23, 0x8c, 0xab, 0x93, 0x6b,
	0x6d, 0x00, 0x8d, 0xb7, 0xbe, 0xef, 0x2c, 0x6f, 0x09, 0xff, 0x8d, 0x3e, 0xad, 0x03, 0xe8, 0x1d,
	0x71, 0x88, 0x20, 0x85, 0x69, 0x37, 0xd0, 0xba, 0x72, 0x7d, 0x16, 0x88, 0xf4, 0x4c, 0x76, 0x5c,
	0x40, 0x8f, 0x01, 0x65, 0x19, 0x8c, 0x5b, 0x59, 0xb7, 0x36, 0x06, 0x1b, 0x3a, 0x48, 0x6a, 0x94,
	0xb6, 0x12, 0x3a, 0x84, 0x6b, 0x8d, 0xc2, 0xd1, 0x08, 0xd3, 0xa2, 0xca, 0xfe, 0x43, 0xd0, 0x0b,
	0x68, 0x7c, 0xf6, 0xc4, 0x5f, 0x44, 0xd5, 0x41, 0x11, 0x98, 0xc6, 0xde, 0xe1, 0xb2, 0xf7, 0x6b,
	0x1f, 0xee, 0x44, 0x38, 0x93, 0x60, 0x61, 0x4f, 0x08, 0xfa, 0x0a, 0xb0, 0xa6, 0x00, 0x9d, 0xe5,
	0x4d, 0x3b, 0x83, 0x8e, 0xfa, 0xb0, 0x48, 0x16, 0xc1, 0xa4, 0xed, 0xa1, 0x21, 0x54, 0x12, 0x36,
	0xd0, 0x83, 0xbc, 0x5b, 0x1b, 0xe4, 0xa8, 0xdb, 0x79, 0xd3, 0xf6, 0xd0, 0x27, 0x80, 0x35, 0x42,
	0xf9, 0xc5, 0x66, 0x10, 0xdb, 0xed, 0xf8, 0x11, 0x6a, 0x29, 0xa0, 0x50, 0xee, 0x83, 0x65, 0x89,
	0x53, 0xef, 0x65, 0xfe, 0xb0, 0x17, 0xe1, 0xfb, 0x58, 0xdb, 0x43, 0x16, 0x1c, 0x27, 0xef, 0x83,
	0x34, 0x79, 0xe8, 0x3c, 0xbf, 0x8a, 0x2d, 0x84, 0xee, 0x2e, 0x7a, 0x08, 0x95, 0x04, 0xb4, 0xfc,
	0xa6, 0x6e, 0x60, 0x58, 0xd8, 0xd4, 0x35, 0x4d, 0xf9, 0x4d, 0xcd, 0xd0, 0xb6, 0xd3, 0x71, 0xd0,
	0xff, 0xf2, 0x8c, 0xda, 0xe2, 0xfb, 0xdc, 0xd2, 0x27, 0xcc, 0x35, 0x62, 0x61, 0xf4, 0x75, 0xd2,
	0x29, 0x33, 0x6e, 0x7d, 0xf9, 0x5e, 0xf9, 0xeb, 0x9f, 0xd6, 0xa1, 0xd4, 0x3c, 0xfd, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x3e, 0x54, 0x1b, 0x12, 0x1d, 0x07, 0x00, 0x00,
}
