// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment/v0/image.proto

package pdeployment // import "github.com/n0stack/proto.go/deployment/v0"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import v0 "github.com/n0stack/proto.go/provisioning/v0"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Image struct {
	Name                    string                          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Annotations             map[string]string               `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version                 uint64                          `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	RegisteredBlockStorages []*Image_RegisteredBlockStorage `protobuf:"bytes,50,rep,name=registered_block_storages,json=registeredBlockStorages" json:"registered_block_storages,omitempty"`
	Tags                    map[string]string               `protobuf:"bytes,51,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral    struct{}                        `json:"-"`
	XXX_unrecognized        []byte                          `json:"-"`
	XXX_sizecache           int32                           `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{0}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Image) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Image) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Image) GetRegisteredBlockStorages() []*Image_RegisteredBlockStorage {
	if m != nil {
		return m.RegisteredBlockStorages
	}
	return nil
}

func (m *Image) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Image_RegisteredBlockStorage struct {
	BlockStorageName     string               `protobuf:"bytes,1,opt,name=block_storage_name,json=blockStorageName" json:"block_storage_name,omitempty"`
	RegisteredAt         *timestamp.Timestamp `protobuf:"bytes,2,opt,name=registered_at,json=registeredAt" json:"registered_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Image_RegisteredBlockStorage) Reset()         { *m = Image_RegisteredBlockStorage{} }
func (m *Image_RegisteredBlockStorage) String() string { return proto.CompactTextString(m) }
func (*Image_RegisteredBlockStorage) ProtoMessage()    {}
func (*Image_RegisteredBlockStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{0, 1}
}
func (m *Image_RegisteredBlockStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image_RegisteredBlockStorage.Unmarshal(m, b)
}
func (m *Image_RegisteredBlockStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image_RegisteredBlockStorage.Marshal(b, m, deterministic)
}
func (dst *Image_RegisteredBlockStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image_RegisteredBlockStorage.Merge(dst, src)
}
func (m *Image_RegisteredBlockStorage) XXX_Size() int {
	return xxx_messageInfo_Image_RegisteredBlockStorage.Size(m)
}
func (m *Image_RegisteredBlockStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_Image_RegisteredBlockStorage.DiscardUnknown(m)
}

var xxx_messageInfo_Image_RegisteredBlockStorage proto.InternalMessageInfo

func (m *Image_RegisteredBlockStorage) GetBlockStorageName() string {
	if m != nil {
		return m.BlockStorageName
	}
	return ""
}

func (m *Image_RegisteredBlockStorage) GetRegisteredAt() *timestamp.Timestamp {
	if m != nil {
		return m.RegisteredAt
	}
	return nil
}

type ListImagesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListImagesRequest) Reset()         { *m = ListImagesRequest{} }
func (m *ListImagesRequest) String() string { return proto.CompactTextString(m) }
func (*ListImagesRequest) ProtoMessage()    {}
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{1}
}
func (m *ListImagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListImagesRequest.Unmarshal(m, b)
}
func (m *ListImagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListImagesRequest.Marshal(b, m, deterministic)
}
func (dst *ListImagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListImagesRequest.Merge(dst, src)
}
func (m *ListImagesRequest) XXX_Size() int {
	return xxx_messageInfo_ListImagesRequest.Size(m)
}
func (m *ListImagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListImagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListImagesRequest proto.InternalMessageInfo

type ListImagesResponse struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=Images" json:"Images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListImagesResponse) Reset()         { *m = ListImagesResponse{} }
func (m *ListImagesResponse) String() string { return proto.CompactTextString(m) }
func (*ListImagesResponse) ProtoMessage()    {}
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{2}
}
func (m *ListImagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListImagesResponse.Unmarshal(m, b)
}
func (m *ListImagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListImagesResponse.Marshal(b, m, deterministic)
}
func (dst *ListImagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListImagesResponse.Merge(dst, src)
}
func (m *ListImagesResponse) XXX_Size() int {
	return xxx_messageInfo_ListImagesResponse.Size(m)
}
func (m *ListImagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListImagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListImagesResponse proto.InternalMessageInfo

func (m *ListImagesResponse) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type GetImageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetImageRequest) Reset()         { *m = GetImageRequest{} }
func (m *GetImageRequest) String() string { return proto.CompactTextString(m) }
func (*GetImageRequest) ProtoMessage()    {}
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{3}
}
func (m *GetImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetImageRequest.Unmarshal(m, b)
}
func (m *GetImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetImageRequest.Marshal(b, m, deterministic)
}
func (dst *GetImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetImageRequest.Merge(dst, src)
}
func (m *GetImageRequest) XXX_Size() int {
	return xxx_messageInfo_GetImageRequest.Size(m)
}
func (m *GetImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetImageRequest proto.InternalMessageInfo

func (m *GetImageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ApplyImageRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version              uint64            `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ApplyImageRequest) Reset()         { *m = ApplyImageRequest{} }
func (m *ApplyImageRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyImageRequest) ProtoMessage()    {}
func (*ApplyImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{4}
}
func (m *ApplyImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyImageRequest.Unmarshal(m, b)
}
func (m *ApplyImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyImageRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyImageRequest.Merge(dst, src)
}
func (m *ApplyImageRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyImageRequest.Size(m)
}
func (m *ApplyImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyImageRequest proto.InternalMessageInfo

func (m *ApplyImageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplyImageRequest) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *ApplyImageRequest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type DeleteImageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteImageRequest) Reset()         { *m = DeleteImageRequest{} }
func (m *DeleteImageRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteImageRequest) ProtoMessage()    {}
func (*DeleteImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{5}
}
func (m *DeleteImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteImageRequest.Unmarshal(m, b)
}
func (m *DeleteImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteImageRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteImageRequest.Merge(dst, src)
}
func (m *DeleteImageRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteImageRequest.Size(m)
}
func (m *DeleteImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteImageRequest proto.InternalMessageInfo

func (m *DeleteImageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegisterBlockStorageRequest struct {
	ImageName            string   `protobuf:"bytes,1,opt,name=image_name,json=imageName" json:"image_name,omitempty"`
	BlockStorageName     string   `protobuf:"bytes,2,opt,name=block_storage_name,json=blockStorageName" json:"block_storage_name,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterBlockStorageRequest) Reset()         { *m = RegisterBlockStorageRequest{} }
func (m *RegisterBlockStorageRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterBlockStorageRequest) ProtoMessage()    {}
func (*RegisterBlockStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{6}
}
func (m *RegisterBlockStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterBlockStorageRequest.Unmarshal(m, b)
}
func (m *RegisterBlockStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterBlockStorageRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterBlockStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterBlockStorageRequest.Merge(dst, src)
}
func (m *RegisterBlockStorageRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterBlockStorageRequest.Size(m)
}
func (m *RegisterBlockStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterBlockStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterBlockStorageRequest proto.InternalMessageInfo

func (m *RegisterBlockStorageRequest) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *RegisterBlockStorageRequest) GetBlockStorageName() string {
	if m != nil {
		return m.BlockStorageName
	}
	return ""
}

func (m *RegisterBlockStorageRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateBlockStorageRequest struct {
	ImageName            string            `protobuf:"bytes,1,opt,name=image_name,json=imageName" json:"image_name,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestBytes         uint64            `protobuf:"varint,10,opt,name=request_bytes,json=requestBytes" json:"request_bytes,omitempty"`
	LimitBytes           uint64            `protobuf:"varint,11,opt,name=limit_bytes,json=limitBytes" json:"limit_bytes,omitempty"`
	Tag                  string            `protobuf:"bytes,100,opt,name=tag" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateBlockStorageRequest) Reset()         { *m = CreateBlockStorageRequest{} }
func (m *CreateBlockStorageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBlockStorageRequest) ProtoMessage()    {}
func (*CreateBlockStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{7}
}
func (m *CreateBlockStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlockStorageRequest.Unmarshal(m, b)
}
func (m *CreateBlockStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlockStorageRequest.Marshal(b, m, deterministic)
}
func (dst *CreateBlockStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlockStorageRequest.Merge(dst, src)
}
func (m *CreateBlockStorageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBlockStorageRequest.Size(m)
}
func (m *CreateBlockStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlockStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlockStorageRequest proto.InternalMessageInfo

func (m *CreateBlockStorageRequest) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *CreateBlockStorageRequest) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *CreateBlockStorageRequest) GetRequestBytes() uint64 {
	if m != nil {
		return m.RequestBytes
	}
	return 0
}

func (m *CreateBlockStorageRequest) GetLimitBytes() uint64 {
	if m != nil {
		return m.LimitBytes
	}
	return 0
}

func (m *CreateBlockStorageRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type TagImageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	BlockStorageName     string   `protobuf:"bytes,2,opt,name=block_storage_name,json=blockStorageName" json:"block_storage_name,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagImageRequest) Reset()         { *m = TagImageRequest{} }
func (m *TagImageRequest) String() string { return proto.CompactTextString(m) }
func (*TagImageRequest) ProtoMessage()    {}
func (*TagImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{8}
}
func (m *TagImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagImageRequest.Unmarshal(m, b)
}
func (m *TagImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagImageRequest.Marshal(b, m, deterministic)
}
func (dst *TagImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagImageRequest.Merge(dst, src)
}
func (m *TagImageRequest) XXX_Size() int {
	return xxx_messageInfo_TagImageRequest.Size(m)
}
func (m *TagImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagImageRequest proto.InternalMessageInfo

func (m *TagImageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TagImageRequest) GetBlockStorageName() string {
	if m != nil {
		return m.BlockStorageName
	}
	return ""
}

func (m *TagImageRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type UntagImageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UntagImageRequest) Reset()         { *m = UntagImageRequest{} }
func (m *UntagImageRequest) String() string { return proto.CompactTextString(m) }
func (*UntagImageRequest) ProtoMessage()    {}
func (*UntagImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_image_02bad2b0b203884e, []int{9}
}
func (m *UntagImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UntagImageRequest.Unmarshal(m, b)
}
func (m *UntagImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UntagImageRequest.Marshal(b, m, deterministic)
}
func (dst *UntagImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UntagImageRequest.Merge(dst, src)
}
func (m *UntagImageRequest) XXX_Size() int {
	return xxx_messageInfo_UntagImageRequest.Size(m)
}
func (m *UntagImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UntagImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UntagImageRequest proto.InternalMessageInfo

func (m *UntagImageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UntagImageRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func init() {
	proto.RegisterType((*Image)(nil), "n0stack.deployment.Image")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.deployment.Image.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.deployment.Image.TagsEntry")
	proto.RegisterType((*Image_RegisteredBlockStorage)(nil), "n0stack.deployment.Image.RegisteredBlockStorage")
	proto.RegisterType((*ListImagesRequest)(nil), "n0stack.deployment.ListImagesRequest")
	proto.RegisterType((*ListImagesResponse)(nil), "n0stack.deployment.ListImagesResponse")
	proto.RegisterType((*GetImageRequest)(nil), "n0stack.deployment.GetImageRequest")
	proto.RegisterType((*ApplyImageRequest)(nil), "n0stack.deployment.ApplyImageRequest")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.deployment.ApplyImageRequest.AnnotationsEntry")
	proto.RegisterType((*DeleteImageRequest)(nil), "n0stack.deployment.DeleteImageRequest")
	proto.RegisterType((*RegisterBlockStorageRequest)(nil), "n0stack.deployment.RegisterBlockStorageRequest")
	proto.RegisterType((*CreateBlockStorageRequest)(nil), "n0stack.deployment.CreateBlockStorageRequest")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.deployment.CreateBlockStorageRequest.AnnotationsEntry")
	proto.RegisterType((*TagImageRequest)(nil), "n0stack.deployment.TagImageRequest")
	proto.RegisterType((*UntagImageRequest)(nil), "n0stack.deployment.UntagImageRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ImageService service

type ImageServiceClient interface {
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*Image, error)
	ApplyImage(ctx context.Context, in *ApplyImageRequest, opts ...grpc.CallOption) (*Image, error)
	DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RegisterBlockStorage(ctx context.Context, in *RegisterBlockStorageRequest, opts ...grpc.CallOption) (*Image, error)
	CreateBlockStorage(ctx context.Context, in *CreateBlockStorageRequest, opts ...grpc.CallOption) (*v0.BlockStorage, error)
	TagImage(ctx context.Context, in *TagImageRequest, opts ...grpc.CallOption) (*Image, error)
	UntagImage(ctx context.Context, in *UntagImageRequest, opts ...grpc.CallOption) (*Image, error)
}

type imageServiceClient struct {
	cc *grpc.ClientConn
}

func NewImageServiceClient(cc *grpc.ClientConn) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	out := new(ListImagesResponse)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/ListImages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/GetImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) ApplyImage(ctx context.Context, in *ApplyImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/ApplyImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/DeleteImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) RegisterBlockStorage(ctx context.Context, in *RegisterBlockStorageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/RegisterBlockStorage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) CreateBlockStorage(ctx context.Context, in *CreateBlockStorageRequest, opts ...grpc.CallOption) (*v0.BlockStorage, error) {
	out := new(v0.BlockStorage)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/CreateBlockStorage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) TagImage(ctx context.Context, in *TagImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/TagImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) UntagImage(ctx context.Context, in *UntagImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/n0stack.deployment.ImageService/UntagImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ImageService service

type ImageServiceServer interface {
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	GetImage(context.Context, *GetImageRequest) (*Image, error)
	ApplyImage(context.Context, *ApplyImageRequest) (*Image, error)
	DeleteImage(context.Context, *DeleteImageRequest) (*empty.Empty, error)
	RegisterBlockStorage(context.Context, *RegisterBlockStorageRequest) (*Image, error)
	CreateBlockStorage(context.Context, *CreateBlockStorageRequest) (*v0.BlockStorage, error)
	TagImage(context.Context, *TagImageRequest) (*Image, error)
	UntagImage(context.Context, *UntagImageRequest) (*Image, error)
}

func RegisterImageServiceServer(s *grpc.Server, srv ImageServiceServer) {
	s.RegisterService(&_ImageService_serviceDesc, srv)
}

func _ImageService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/ListImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/GetImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).GetImage(ctx, req.(*GetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_ApplyImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).ApplyImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/ApplyImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).ApplyImage(ctx, req.(*ApplyImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/DeleteImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).DeleteImage(ctx, req.(*DeleteImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_RegisterBlockStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBlockStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).RegisterBlockStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/RegisterBlockStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).RegisterBlockStorage(ctx, req.(*RegisterBlockStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_CreateBlockStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlockStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).CreateBlockStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/CreateBlockStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).CreateBlockStorage(ctx, req.(*CreateBlockStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_TagImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).TagImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/TagImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).TagImage(ctx, req.(*TagImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_UntagImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntagImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).UntagImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.deployment.ImageService/UntagImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).UntagImage(ctx, req.(*UntagImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "n0stack.deployment.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _ImageService_ListImages_Handler,
		},
		{
			MethodName: "GetImage",
			Handler:    _ImageService_GetImage_Handler,
		},
		{
			MethodName: "ApplyImage",
			Handler:    _ImageService_ApplyImage_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _ImageService_DeleteImage_Handler,
		},
		{
			MethodName: "RegisterBlockStorage",
			Handler:    _ImageService_RegisterBlockStorage_Handler,
		},
		{
			MethodName: "CreateBlockStorage",
			Handler:    _ImageService_CreateBlockStorage_Handler,
		},
		{
			MethodName: "TagImage",
			Handler:    _ImageService_TagImage_Handler,
		},
		{
			MethodName: "UntagImage",
			Handler:    _ImageService_UntagImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployment/v0/image.proto",
}

func init() { proto.RegisterFile("deployment/v0/image.proto", fileDescriptor_image_02bad2b0b203884e) }

var fileDescriptor_image_02bad2b0b203884e = []byte{
	// 750 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x6e, 0xfe, 0x7a, 0x4e, 0x26, 0x3d, 0x6a, 0x3a, 0xa7, 0x2a, 0x8e, 0x2b, 0xd4, 0xca, 0x55,
	0x51, 0x84, 0xc0, 0x29, 0xa9, 0xa0, 0xfc, 0x48, 0x45, 0x2d, 0x54, 0x15, 0x52, 0x05, 0xc8, 0x2d,
	0x12, 0x42, 0x42, 0x61, 0x93, 0x2c, 0xc6, 0xaa, 0xed, 0x35, 0xde, 0x4d, 0xa4, 0xdc, 0x70, 0xcb,
	0xd3, 0x70, 0xc7, 0x7b, 0xf0, 0x00, 0xbc, 0x0c, 0xf2, 0xda, 0x49, 0x9c, 0x78, 0x93, 0xd0, 0xf6,
	0xce, 0x9e, 0x7c, 0xf3, 0xfb, 0x7d, 0x33, 0x31, 0xd4, 0xba, 0x34, 0x70, 0xd9, 0xc0, 0xa3, 0xbe,
	0x68, 0xf4, 0xf7, 0x1a, 0x8e, 0x47, 0x6c, 0x6a, 0x06, 0x21, 0x13, 0x0c, 0xd1, 0xdf, 0xe3, 0x82,
	0x74, 0x2e, 0xcd, 0x31, 0x44, 0xdf, 0xb4, 0x19, 0xb3, 0x5d, 0xda, 0x90, 0x88, 0x76, 0xef, 0x73,
	0x83, 0x7a, 0x81, 0x18, 0xc4, 0x0e, 0xfa, 0xd6, 0xf4, 0x8f, 0xc2, 0xf1, 0x28, 0x17, 0xc4, 0x0b,
	0x12, 0xc0, 0x4e, 0x10, 0xb2, 0xbe, 0xc3, 0x1d, 0xe6, 0x3b, 0xbe, 0x1d, 0xa5, 0x6b, 0xbb, 0xac,
	0x73, 0xd9, 0xe2, 0x82, 0x85, 0xa3, 0xb4, 0xc6, 0x8f, 0x22, 0x94, 0x5e, 0x45, 0x65, 0x20, 0x42,
	0xd1, 0x27, 0x1e, 0xd5, 0x72, 0xdb, 0xb9, 0x7a, 0xd9, 0x92, 0xcf, 0x78, 0x06, 0x15, 0xe2, 0xfb,
	0x4c, 0x10, 0xe1, 0x30, 0x9f, 0x6b, 0x85, 0xed, 0x42, 0xbd, 0xd2, 0xbc, 0x6b, 0x66, 0x4b, 0x35,
	0x65, 0x0c, 0xf3, 0x68, 0x0c, 0x3e, 0xf1, 0x45, 0x38, 0xb0, 0xd2, 0xee, 0xa8, 0xc1, 0x3f, 0x7d,
	0x1a, 0x46, 0x05, 0x69, 0xa5, 0xed, 0x5c, 0xbd, 0x68, 0x0d, 0x5f, 0xd1, 0x85, 0x5a, 0x48, 0x6d,
	0x87, 0x0b, 0x1a, 0xd2, 0x6e, 0x6b, 0xa2, 0x4e, 0xae, 0x35, 0x65, 0xd6, 0xbd, 0xd9, 0x59, 0xad,
	0x91, 0xeb, 0x71, 0xe4, 0x79, 0x1e, 0x3b, 0x5a, 0xb7, 0x42, 0xa5, 0x9d, 0xe3, 0x01, 0x14, 0x05,
	0xb1, 0xb9, 0xb6, 0x2f, 0x03, 0xef, 0xcc, 0x0e, 0x7c, 0x41, 0xec, 0xa4, 0x0f, 0xe9, 0xa0, 0x1f,
	0x42, 0x75, 0xba, 0x43, 0xac, 0x42, 0xe1, 0x92, 0x0e, 0x92, 0xa9, 0x45, 0x8f, 0xb8, 0x0e, 0xa5,
	0x3e, 0x71, 0x7b, 0x54, 0xcb, 0x4b, 0x5b, 0xfc, 0xf2, 0x34, 0xff, 0x38, 0xa7, 0x7f, 0xcf, 0xc1,
	0x86, 0xba, 0x58, 0xbc, 0x07, 0x38, 0xd1, 0x76, 0x2b, 0xc5, 0x45, 0xb5, 0x9d, 0x42, 0xbe, 0x8e,
	0x78, 0x79, 0x0e, 0xff, 0xa5, 0xe6, 0x45, 0x84, 0x4c, 0x55, 0x69, 0xea, 0x66, 0xac, 0x09, 0x73,
	0xa8, 0x09, 0xf3, 0x62, 0xa8, 0x09, 0x6b, 0x65, 0xec, 0x70, 0x24, 0xf4, 0x03, 0x28, 0x8f, 0x9a,
	0xbb, 0x4a, 0x0b, 0xc6, 0xff, 0xb0, 0x76, 0xe6, 0x70, 0x21, 0xe7, 0xc3, 0x2d, 0xfa, 0xb5, 0x47,
	0xb9, 0x30, 0x4e, 0x01, 0xd3, 0x46, 0x1e, 0x30, 0x9f, 0x53, 0x7c, 0x00, 0xcb, 0xb1, 0x45, 0xcb,
	0xc9, 0x41, 0xd7, 0x66, 0x0e, 0xda, 0x4a, 0x80, 0xc6, 0x2e, 0xac, 0x9e, 0xd2, 0x38, 0x4e, 0x12,
	0x5b, 0x25, 0x4b, 0xe3, 0x77, 0x0e, 0xd6, 0x8e, 0x82, 0xc0, 0x1d, 0x2c, 0x42, 0xe2, 0x7b, 0x95,
	0x80, 0x1f, 0xa9, 0x0a, 0xc9, 0xc4, 0xbb, 0xae, 0x98, 0x6f, 0xaa, 0x12, 0xa3, 0x0e, 0xf8, 0x92,
	0xba, 0x54, 0xd0, 0x85, 0x73, 0xf8, 0x06, 0x9b, 0x43, 0x39, 0x4d, 0x28, 0x3f, 0x71, 0xb9, 0x0d,
	0x20, 0x2f, 0x4c, 0x5a, 0x4b, 0x65, 0x69, 0x91, 0x22, 0x52, 0x4b, 0x2e, 0x3f, 0x43, 0x72, 0x98,
	0x2c, 0x4d, 0x34, 0xc2, 0x72, 0xbc, 0x0f, 0xc6, 0xcf, 0x3c, 0xd4, 0x5e, 0x84, 0x94, 0x08, 0x7a,
	0x8d, 0xf4, 0x9f, 0x54, 0xd4, 0x1c, 0xaa, 0xa8, 0x99, 0x99, 0x62, 0x01, 0x45, 0x3b, 0xd1, 0x96,
	0x48, 0x60, 0xab, 0x3d, 0x10, 0x94, 0x6b, 0x20, 0x89, 0x5a, 0x49, 0x8c, 0xc7, 0x91, 0x0d, 0xb7,
	0xa0, 0xe2, 0x3a, 0x9e, 0x33, 0x84, 0x54, 0x24, 0x04, 0xa4, 0x29, 0x06, 0x54, 0xa1, 0x20, 0x88,
	0xad, 0x75, 0x63, 0xea, 0x04, 0xb1, 0x6f, 0x4c, 0xb0, 0x0d, 0xab, 0x17, 0xc4, 0x5e, 0xa8, 0xdd,
	0x9b, 0xf3, 0xf3, 0x04, 0xd6, 0xde, 0xf9, 0xe2, 0x2f, 0x52, 0x25, 0x3d, 0xe6, 0x47, 0x3d, 0x36,
	0x7f, 0x95, 0x60, 0x45, 0xba, 0x9d, 0xd3, 0xb0, 0xef, 0x74, 0x28, 0x7e, 0x04, 0x18, 0xef, 0x38,
	0xee, 0xaa, 0x78, 0xca, 0x1c, 0x06, 0xfd, 0xce, 0x22, 0x58, 0x7c, 0x2a, 0x8c, 0x25, 0x3c, 0x83,
	0x7f, 0x87, 0x9b, 0x8f, 0xca, 0x8b, 0x3c, 0x75, 0x17, 0xf4, 0xd9, 0xd7, 0xc4, 0x58, 0xc2, 0xb7,
	0x00, 0xe3, 0x7d, 0x56, 0x17, 0x9b, 0xd9, 0xf7, 0xf9, 0x11, 0xdf, 0x40, 0x25, 0xb5, 0x94, 0xa8,
	0x6c, 0x2c, 0xbb, 0xb5, 0xfa, 0x46, 0xe6, 0x22, 0x9f, 0x44, 0x7f, 0xe1, 0xc6, 0x12, 0x76, 0x61,
	0x5d, 0xb5, 0xbb, 0xd8, 0x50, 0x45, 0x9e, 0xb3, 0xe5, 0xf3, 0xcb, 0x76, 0x00, 0xb3, 0xdb, 0x83,
	0xf7, 0xaf, 0xb4, 0x65, 0xba, 0x31, 0x82, 0xa7, 0xbf, 0x28, 0xcc, 0x34, 0x34, 0x66, 0x70, 0xa8,
	0x6a, 0x35, 0x83, 0x53, 0x9a, 0x5f, 0xc8, 0xe0, 0x58, 0xba, 0x6a, 0x06, 0x33, 0xd2, 0x9e, 0x1b,
	0xf1, 0xf8, 0xe0, 0xc3, 0x43, 0xdb, 0x11, 0x5f, 0x7a, 0x6d, 0xb3, 0xc3, 0xbc, 0x46, 0x02, 0x8c,
	0xbf, 0x9e, 0x4c, 0x9b, 0x35, 0x26, 0xbe, 0xcc, 0x9e, 0x05, 0xe3, 0xd7, 0xf6, 0xb2, 0xc4, 0xec,
	0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x89, 0x02, 0x3b, 0xbd, 0x09, 0x00, 0x00,
}
